### PR TITLE
Prevented Visual Studio crash when opening a connected solution, but …

### LINKED ISSUE #326: VS crashes if SonarQube server is not available
### Description

Opening a bound solution when SQ is not available crashes VS.

### Repro steps

Please provide the steps required to reproduce the problem

1. Bind a solution in VS to a local instance of SonarQube

2. Close the solution

3. Stop the local instance of SonarQube

4. Open the solution

### Expected behavior

P1: VS does not crash

P2: a notification is displayed to the user with a link to allow them to reconnect. This could be split into a separate issue and done later.

### Actual behavior

VS crashes with an unhandled HTTP exception

### Known workarounds

None.

### Related information

* SonarLint for VS Version: 3.6 milestone (in progress)
* Visual Studio Version: 2015u3

### PR DESCRIPTION
**Pull request by valhristov**
…SonarQube server is not available.

Fix #326

### CODE REVIEW

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs [hunk 1]
```diff
@@ -35,6 +36,7 @@ internal sealed class ActiveSolutionBoundTracker : IActiveSolutionBoundTracker,
         private readonly IActiveSolutionTracker solutionTracker;
         private readonly IErrorListInfoBarController errorListInfoBarController;
         private readonly ISolutionBindingInformationProvider solutionBindingInformationProvider;
+        private ISonarLintOutput sonarLintOutput;
```
Comment (SonarTech) [inline src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: MAJOR Make 'sonarLintOutput' 'readonly'. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=csharpsquid%3AS2933)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs [hunk 2]
```diff
@@ -43,20 +45,25 @@ internal sealed class ActiveSolutionBoundTracker : IActiveSolutionBoundTracker,
         public string ProjectKey { get; private set; }
 
         [ImportingConstructor]
-        public ActiveSolutionBoundTracker(IHost host, IActiveSolutionTracker activeSolutionTracker)
+        public ActiveSolutionBoundTracker(IHost host, IActiveSolutionTracker activeSolutionTracker,
+            ISonarLintOutput sonarLintOutput)
```
Comment (Evangelink) [inline src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: I know this was already merged previously but I would have named the interface `ISonarLintLogger`.

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs [hunk 3]
```diff
@@ -102,17 +108,28 @@ public ActiveSolutionBoundTracker(IHost host, IActiveSolutionTracker activeSolut
...
-
-                // TODO: handle connection failure
-                // TODO: block until the connection is complete
-                await this.extensionHost.SonarQubeService.ConnectAsync(connectionInformation, CancellationToken.None);
+                try
+                {
+                    var connectionInformation = GetConnectionInformation();
+                    await sonarQubeService.ConnectAsync(connectionInformation, CancellationToken.None);
+                }
+                catch (Exception ex)
```
Comment (Evangelink) [inline src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: Don't know how useful it could be but isn't it better to create some helper that will handle the different catch as in `ConnectionWorkflow.cs` and display different messages?

File: src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs [hunk 4]
```diff
@@ -110,6 +115,38 @@ public void ActiveSolutionBoundTracker_Initialisation_Bound()
         }
 
         [TestMethod]
+        public void ActiveSolutionBoundTracker_When_ConnectAsync_Throws_Write_To_Output()
+        {
+            // Arrange
+            var sonarLintOutputMock = new Mock<ISonarLintOutput>();
```
Comment (Evangelink) [inline src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs]: Why not use `this.sonarLintOutputMock`?

File: src/Integration/Helpers/SonarLintOutput.cs [hunk 5]
```diff
@@ -18,10 +18,13 @@
  * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
  */
 
+using System.ComponentModel.Composition;
 using Microsoft.VisualStudio.Shell;
 
 namespace SonarLint.VisualStudio.Integration
 {
+    [Export(typeof(ISonarLintOutput))]
+    [PartCreationPolicy(CreationPolicy.Shared)]
```
Comment (Evangelink) [inline src/Integration/Helpers/SonarLintOutput.cs]: Here we go....I was afraid of the time this would come xD

File: src/Integration.Vsix/SonarLintNotificationsPackage.cs [hunk 6]
```diff
@@ -62,7 +61,8 @@ protected override void Initialize()
             var sonarqubeService = this.GetMefService<ISonarQubeService>();
 
             notifications = new SonarQubeNotificationService(sonarqubeService,
-                new NotificationIndicatorViewModel(), new TimerWrapper { Interval = 60000 }, output);
+                new NotificationIndicatorViewModel(), new TimerWrapper { Interval = 60000 },
+                this.GetMefService<ISonarLintOutput>());
```
Comment (Evangelink) [inline src/Integration.Vsix/SonarLintNotificationsPackage.cs]: Let's store it into some variable instead of asking for it here and later on.

Comment (valhristov) [reply src/Integration.Vsix/SonarLintNotificationsPackage.cs]: I was not sure if `Initialize()` is always called **before** `OnLoadOptions()`. Probably it is safe, but I could not find documentation about the order of invocation. On the other hand, the exception should not be thrown very often and the service resolution should not put performance penalty.

File: src/Integration/Helpers/SonarLintOutput.cs (hunk 5 above)
Comment (valhristov) [reply src/Integration/Helpers/SonarLintOutput.cs]: Magic, eh :)

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs (hunk 2 above)
Comment (valhristov) [reply src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: I don't know... Logger has different semantic - you usually put trace level in the calls, here we just write something to the window. It is similar though, we could rename in a separate commit/ticket.

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs (hunk 3 above)
Comment (valhristov) [reply src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: Makes sense.

File: src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs (hunk 4 above)
Comment (valhristov) [reply src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs]: Because I am blind...

File: src/Integration.Vsix/SonarLintNotificationsPackage.cs (hunk 6 above)
Comment (duncanp-sonar) [reply src/Integration.Vsix/SonarLintNotificationsPackage.cs]: _Initialize_ is called as part of the package being "sited" (i.e. started and hooked in to VS - the underlying native interface method is called _SetSite_). It **should** happen before any other methods get called.

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs [hunk 7]
```diff
@@ -102,17 +108,28 @@ public ActiveSolutionBoundTracker(IHost host, IActiveSolutionTracker activeSolut
...
+                {
+                    sonarLintOutput.Write($"Cannot connect to SonarQube: '{ex.Message}'");
```
Comment (duncanp-sonar) [inline src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: Out of interest, does the output window message add timestamp? It might be useful to get an idea of the rate at which errors are occurring.

Comment (Evangelink) [reply src/Integration/MefServices/ActiveSolutionBoundTracker.cs]: It currently doesn't.
