### PR TITLE
Guard against quick fix gold bar

### LINKED ISSUE #3122: Goldbar thrown when opening and quickly closing a .ts file
### Description

VS displays a gold bar complaining about an unhandled exception in SonarLint.

### Repro steps
Not reliably reproducible.
Happened once when opening a folder and adding new .ts file and opening it for the first time.

### Call stack
From activitylog:

```
System.ObjectDisposedException: Cannot access a disposed object.&#x000D;&#x000A;Object name: &apos;TagAggregator&apos;.&#x000D;&#x000A;   
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GetTags(SnapshotSpan span)&#x000D;&#x000A;   
at SonarLint.VisualStudio.IssueVisualization.Editor.QuickActions.QuickFixes.QuickFixActionsSource.IsOnIssueWithApplicableQuickFixes(SnapshotSpan range, IEnumerable`1&amp; issuesWithFixes)&#x000D;&#x000A;   
at SonarLint.VisualStudio.IssueVisualization.Editor.QuickActions.QuickFixes.QuickFixActionsSource.&lt;&gt;c__DisplayClass12_0.&lt;HasSuggestedActionsAsync&gt;b__0()&#x000D;&#x000A;   
at SonarLint.VisualStudio.Infrastructure.VS.RunOnUIThread.&lt;&gt;c__DisplayClass1_0.&lt;&lt;RunAsync&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#x000D;&#x000A;   
at SonarLint.VisualStudio.Infrastructure.VS.RunOnUIThread.&lt;RunAsync&gt;d__1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#x000D;&#x000A;   
at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.&lt;RunOnUIThread&gt;d__3.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#x000D;&#x000A;   
at SonarLint.VisualStudio.IssueVisualization.Editor.QuickActions.QuickFixes.QuickFixActionsSource.&lt;HasSuggestedActionsAsync&gt;d__12.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.&lt;CallExtensionPointAsync&gt;d__39`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### Notes
Looks like a race/timing issue: VS is asking for quick fixes for a document, and is also cleaning up the document infrastructure because it has been closed.

We'll add a defensive try-catch.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #3122

### CODE REVIEW

File: src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs [hunk 1]
```diff
@@ -74,21 +74,28 @@ internal sealed class QuickFixActionsSource : ISuggestedActionsSource
...
 
         public IEnumerable<SuggestedActionSet> GetSuggestedActions(
-            ISuggestedActionCategorySet requestedActionCategories, 
+            ISuggestedActionCategorySet requestedActionCategories,
             SnapshotSpan range,
             CancellationToken cancellationToken)
         {
             var allActions = new List<ISuggestedAction>();
 
-            if (IsOnIssueWithApplicableQuickFixes(range, out var issuesWithFixes))
```
Comment (duncanp-sonar) [inline src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs:83]: The GitHub diff isn't helpful here. None of the existing code has changed. It's just been moved inside the try-catch.

Same for the other method.

File: src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs [hunk 2]
```diff
@@ -74,21 +74,28 @@ internal sealed class QuickFixActionsSource : ISuggestedActionsSource
...
+                        var applicableFixes = issueViz.QuickFixes.Where(x => x.CanBeApplied(textView.TextSnapshot));
 
-                    allActions.AddRange(applicableFixes.Select(fix => new QuickFixSuggestedAction(fix, textView.TextBuffer, issueViz, quickFixesTelemetryManager, logger)));
+                        allActions.AddRange(applicableFixes.Select(fix => new QuickFixSuggestedAction(fix, textView.TextBuffer, issueViz, quickFixesTelemetryManager, logger)));
+                    }
                 }
             }
+            catch (Exception ex) when (!ErrorHandler.IsCriticalException(ex))
+            {
+                logger.WriteLine(string.Format(Resources.ERR_QuickFixes_Exception, ex));
```
Comment (duncanp-sonar) [inline src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs:97]: I opted to log the entire call stack at normal verbosity. The issue is timing-related and hard to reproduce so we don't expect it to occur often.
If we log it at debug verbosity there's no chance we'll ever see it reported in the wild by users.

File: src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs [hunk 3]
```diff
@@ -74,21 +74,28 @@ internal sealed class QuickFixActionsSource : ISuggestedActionsSource
         public event EventHandler<EventArgs> SuggestedActionsChanged;
 
         public IEnumerable<SuggestedActionSet> GetSuggestedActions(
-            ISuggestedActionCategorySet requestedActionCategories, 
+            ISuggestedActionCategorySet requestedActionCategories,
```
Comment (duncanp-sonar) [inline src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs:77]: The call stack in the bug is for the other public method on the interface, but I decided to add a try-catch to this method too as logically it might occur here too.

The interface methods are `HasX` and `GetX`. The naming suggests VS will call `HasX` first then call `GetX` after. At a guess, the same error might occur here if the timing is slightly different.

File: src/IssueViz/Resources.resx [hunk 4]
```diff
@@ -138,4 +138,7 @@
   <data name="IssueVisualizationToolWindowCaption" xml:space="preserve">
     <value>SonarLint Issue Visualization</value>
   </data>
+  <data name="ERR_QuickFixes_Exception" xml:space="preserve">
+    <value>[Quick fixes] Error processing quick fixes: {0}</value>
```
Comment (duncanp-sonar) [inline src/IssueViz/Resources.resx:142]: I used the same message for both `catch` blocks. The call stack will tell us where it occured.

**Comment by duncanp-sonar** [comment]
I manually tested that quick fixes still work for C++ with this change.

I also tried to test JS and TS quick fixes using the files added to the samples in [this commit](https://github.com/SonarSource/sonarlint-visualstudio-sampleprojects/commit/0410ced37dc66808204e68c2401d5709219abf90), but they didn't appear.
However, they don't appear when I use the last released version of SLVS either so it's not a regression.
I don't know if the problem is the sample project or whether it's a bug in the code.

**Review by rita-sonarsource — APPROVED** [review]

**Review by ugras-ergun-sonarsource — APPROVED** [review]
