### PR TITLE
Remove binding redirects

### LINKED ISSUE #850: SLVS vsix includes the wrong version of System.Interactive.Async
### Description

The SLVS daemon code uses gRPC to communicate with the out-of-process Java daemon.
As a result, the VSIX include the `Grpc.Core` assembly and the `System.Interactive.Async` assembly it depends on. However, the VSIX does not include the version of the `System.Interactive.Async` dll used by the `Grpc.Core` assemblies.

#### Why does the VSIX include the wrong assembly?
Grpc.Core NuGet v1.4.1 references System.Interactive.Async NuGet v3.1.1.
However, Grpc.Core only targets net45 and netstandard1.5, whereas System.Interactive.Async ("SIA") targets net45, net46, netstandard1.0 and netstandard1.3.

Our project targets net46.
VS picks the assemblies in Grpc.Core net45 as the closest version match, and SIA net46.
Unfortunately, Grpc.Core net45 references SIA v3.0.1000.0, and SIA net46 has a dll with version v3.0.3000.0

-> the VSIX contains SIA v3.0.3000.0.

#### How did this ever work?
To work round this issue, our code included a `ProvideBindingRedirection` attribute to redirect all lower versions of SIA to v3.0.3000.0 (the VSSDK targets convert this into a pkgdef file which is embedded in the VSIX; VS applies the redirect as a BindingRedirect in a per-user version of devenv.exe.config).

### Required changes
* changing the VSIX packaging to include the correct version of `System.Interactive.Async`.
* remove the unnecessary `[ProvideBindingRediretion]` attributes

Related issue: #818. In that bug, the crash was happening because VS was not always respecting the binding redirect specified in the `pkgdef` file in the VSIX

### Additional information
* SonarLint for VS Version: v4.8

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixed #850

### CODE REVIEW

File: src/Integration.TeamExplorer.UnitTests/ReferencesTests.cs [hunk 1]
```diff
@@ -32,23 +32,17 @@ public class ReferencesTests
         [TestMethod]
         public void MicrosoftTeamFoundationClient_EnsureCorrectVersion()
         {
-            var tfClientAssemblyVersion = typeof(TeamExplorerController)
-                .Assembly
-                .GetReferencedAssemblies()
-                .FirstOrDefault(ra => ra.Name == "Microsoft.TeamFoundation.Client")
-                ?.Version;
```
Comment (duncanp-sonar) [inline src/Integration.TeamExplorer.UnitTests/ReferencesTests.cs]: Miscellaneous: factored out to a helper method (now used four times)

File: src/Integration.TeamExplorer.UnitTests/app.config [hunk 2]
```diff
@@ -70,14 +70,6 @@
...
         <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
       </dependentAssembly>
-      <dependentAssembly>
-        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
-        <bindingRedirect oldVersion="0.0.0.0-3.6.1.0" newVersion="3.6.1.0" />
-      </dependentAssembly>
-      <dependentAssembly>
-        <assemblyIdentity name="System.Interactive.Async" publicKeyToken="94bc3704cddfc263" culture="neutral" />
-        <bindingRedirect oldVersion="0.0.0.0-3.0.3000.0" newVersion="3.0.3000.0" />
-      </dependentAssembly>
```
Comment (duncanp-sonar) [inline src/Integration.TeamExplorer.UnitTests/app.config]: Miscellaneous: removed unnecessary redirects from app.config files

File: src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs [hunk 3]
```diff
@@ -93,6 +93,24 @@ public void Install_Reinstall_Run()
...
+
+            var grpcCoreAsm = AssemblyHelper.GetVersionOfReferencedAssembly(typeof(VSIX.SonarLintDaemon), "Grpc.Core");
+            grpcCoreAsm.Should().NotBeNull("Cannot locate the Grpc.Core assembly referenced by SonarLint");
+            grpcCoreAsm.Should().Be(new Version(1, 0, 0, 0),
+                "SonarLint not referencing the expected version of Grpc.Core. Does this test need to be updated?");
+
+            var siaAsm = AssemblyHelper.GetVersionOfReferencedAssembly(typeof(VSIX.SonarLintDaemon), "System.Interactive.Async");
+            siaAsm.Should().Be(new Version("3.0.1000.0"),
+                "SonarLint is not using the version of System.Interactive.Async expected by Grpc.Core. This will cause a runtime error.");
+        }
```
Comment (duncanp-sonar) [inline src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs]: New test to check the built assembly references the expected versions.

File: src/Integration.Vsix/packages.config [hunk 4]
```diff
@@ -57,7 +57,7 @@
   <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net46" />
   <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net46" />
   <package id="System.Globalization" version="4.3.0" targetFramework="net46" />
-  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net46" />
+  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net45" />
```
Comment (duncanp-sonar) [inline src/Integration.Vsix/packages.config]: Setting this to `net45` probably doesn't make any difference, but doesn't do any harm.
