### PR TITLE
Handle project types without project-level binder

### LINKED ISSUE #3129: [Binding] Binding a NodeJS project fails
### Description

Attempting to bind a new NodeJS project fails with a null ref exception.

### Repro steps
1. Create a new NodeJS project
2. Attempt to bind it to a Sonar project

### Expected behaviour
Solution is bound successfully

### Actual behaviour
Binding fails.

image

#### Output window text
```
Connecting to SonarQube server: Downloading server settings.
Establishing new binding...
Binding solution to SonarQube project: Started
Binding solution to SonarQube project: Discovering solution projects
   Included projects:
   * Bound_Security_JS.njsproj
   Excluded projects:
   * None (for selected SonarQube project's quality profile)
   You can change the exclusion options via the SonarLint project-level context menu i.e. Solution Explorer -> Select project(s)
Binding solution to SonarQube project: Download quality profile(s):
   Successfully downloaded quality profile. Name: 'Sonar way', Key: 'AWJypR-No-4kJLXn1_rN', Language: 'JavaScript'
   Successfully downloaded quality profile. Name: 'Sonar way', Key: 'AWJypR-No-4kJLXn1_rM', Language: 'TypeScript'
INFO: SonarLint connected mode no longer installs the analyzers NuGet packages. The analyzers embedded in the VSIX are used instead.
Binding solution to SonarQube project: Generating project rule sets
Ruleset binding: initial binding. All projects need to be updated to reference the generated ruleset.
Unexpected error during workflow execution: Object reference not set to an instance of an object..
```

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #3129

### CODE REVIEW

File: src/Integration/Binding/SolutionBindingOperation.cs [hunk 1]
```diff
@@ -171,13 +171,16 @@ public void Prepare(CancellationToken token)
                     return;
                 }
 
-                var languageForProject = projectToLanguageMapper.GetAllBindingLanguagesForProject(project).First();
-                var bindingConfigFile = GetBindingConfig(languageForProject);
```
Comment (duncanp-sonar) [inline src/Integration/Binding/SolutionBindingOperation.cs:175]: The `languageForProject` and `bindingConfigFile` are only required if there is a project-level binder, so I moved those calls inside the new `if`.

File: src/Integration/LocalServices/ProjectSystemHelper.cs [hunk 2]
```diff
@@ -45,6 +44,7 @@ internal class ProjectSystemHelper : IProjectSystemHelper
         internal const string VbCoreProjectKind = "{778DAE3C-4631-46EA-AA77-85C1314464D9}";
         internal const string CSharpCoreProjectKind = "{9A19103F-16F7-4668-BE54-9A1E7A4F7556}";
         internal const string CppProjectKind = "{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}";
+        internal const string NodeJSProjectKind = "{9092aa53-fb77-4645-b42d-1ccca6bd08bd}";
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ProjectSystemHelper.cs:47]: This new constant is currently only used in the tests. However, I'll leave it here for consistency.

**Review by rita-sonarsource — APPROVED** [review]
