### PR TITLE
Fix calling init-linter when eslint-bridge process crashes

### LINKED ISSUE #2409: init-linter is not called again when eslint-bridge process crashes
#### Description

Analysis will fail if eslint-bridge process crashes after the server was initialized successfully with init-linter.

Steps to reproduce:
1. Analyze a ts file --> eslint-bridge process starts, init-linter is called, analysis is successful
2. Open task manager and kill nodejs processes under Visual Studio
3. Re-analyze a ts file

Expected --> analysis is successful
Actual --> analysis fails with `GENERAL_ERROR Linter is undefined. Did you call /init-linter?`
Subsequent analysis also fails.

### PR DESCRIPTION
**Pull request by rita-sonarsource**
Re-fix #2409

### CODE REVIEW

File: src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs [hunk 1]
```diff
@@ -116,15 +100,7 @@ public async Task<AnalysisResponse> Analyze(string filePath, string tsConfigFile
                 TSConfigFilePaths = tsConfigFilePaths
             };
 
-            var result = await eslintBridgeProcess.Start();
```
Comment (rita-sonarsource) [inline src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs:119]: I had to revert this change. My original reasoning for this change was that:
1. The process could die and start again on the same port, so the old `if port != currentPort` logic is flawed.
2. This class is the one that knows that a process was spawned, so why shouldn't it return this information back to the callers.

And for JS that worked, `EslintBridgeClient.Analyze` got back the response that this is a new process, threw an exception and init-linter was called.
But for TS, unfortunately TsConfigProvider was called first, which ignored the `IsNewProcess` flag completely. `EslintBridgeClient.Analyze` then received `IsNewProcess=false` and init-linter was not called. This bug happened only after the process died, since the init-linter was always called at least once.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 2]
```diff
@@ -70,28 +70,22 @@ internal sealed class EslintBridgeAnalyzer : IEslintBridgeAnalyzer
...
         {
             await EnsureEslintBridgeClientIsInitialized(rulesProvider.GetActiveRulesConfiguration(), cancellationToken);
-
             var analysisResponse = await eslintBridgeClient.Analyze(filePath, tsConfig, cancellationToken);
 
             if (analysisResponse.ParsingError != null)
             {
-                LogParsingError(filePath, analysisResponse.ParsingError);
-                return Array.Empty<IAnalysisIssue>();
+                if (analysisResponse.ParsingError.Message.Contains(Resources.ERR_ParsingError_LinterNotInitialized))
```
Comment (rita-sonarsource) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:79]: This is now the bug fix: I decided to leave the decision up to eslint-bridge itself. If it returns an error that init-linter should be called, I call it.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 3]
```diff
@@ -70,28 +70,22 @@ internal sealed class EslintBridgeAnalyzer : IEslintBridgeAnalyzer
...
+                {
+                    await eslintBridgeClient.InitLinter(rulesProvider.GetActiveRulesConfiguration(), cancellationToken);
```
Comment (rita-sonarsource) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:81]: I thought about using recursion and just re-invoking this method, but I was worried about somehow getting stuck in an infinite loop. So I'm just directly calling  `eslintBridgeClient.InitLinter` and `eslintBridgeClient.Analyze`.

File: src/TypeScript/Analyzer/Resources.resx [hunk 4]
```diff
@@ -123,6 +123,9 @@
   <data name="ERR_ParsingError_General" xml:space="preserve">
     <value>Failed to parse file '{0}' at line {1}: {2} {3}</value>
   </data>
+  <data name="ERR_ParsingError_LinterNotInitialized" xml:space="preserve">
+    <value>Linter is undefined</value>
```
Comment (duncanp-sonar) [inline src/TypeScript/Analyzer/Resources.resx:127]: Isn't this a constant value defined by an external component i.e. `eslintbridge`? Do we know if the returned string is localised? (if it is localised, we have a problem since we only handle a single default language)

Assuming it is an external, non-localised fixed value, it would be better to define it is a constant in the code. There's no reason for it to be a resource.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 2 above)
Comment (duncanp-sonar) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:79]: Perhaps we should ask the JS bubble to return a specific error code so we don't have to parse the string.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 3 above)
Comment (duncanp-sonar) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:81]: The flow isn't quite right - if the second call to `analyze` returns a parsing error then it won't be logged. Logically a parsing failure in the second "analyze" should be handled the same as if it occurred in the first "analyze" i.e.

```
response = await analyze;
if (linter is not initialized)
{
  await init-linter;
  response = await analyze;
}

if (parsing error in response)
{
 ...
}

```

**Review by duncanp-sonar — COMMENTED** [review]
Reverting to the previous approach makes sense, but there are a couple of minor bits that don't look quite right.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 2 above)
Comment (rita-sonarsource) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:79]: Yep, that could be great. I'll ask Tibor about the localization.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 3 above)
Comment (rita-sonarsource) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:81]: Woops, you're right. Nice catch 👍

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 5]
```diff
@@ -74,18 +77,17 @@ public async Task<IReadOnlyCollection<IAnalysisIssue>> Analyze(string filePath,
             await EnsureEslintBridgeClientIsInitialized(rulesProvider.GetActiveRulesConfiguration(), cancellationToken);
             var analysisResponse = await eslintBridgeClient.Analyze(filePath, tsConfig, cancellationToken);
 
+            if (analysisResponse.ParsingError != null && 
+                analysisResponse.ParsingError.Message.Contains(LinterIsNotInitializedError))
+            {
+                await eslintBridgeClient.InitLinter(rulesProvider.GetActiveRulesConfiguration(), cancellationToken);
```
Comment (duncanp-sonar) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:83]: `rulesProvider.GetActiveRulesConfiguration()` was called above. Do we want to recalculate the value, or reuse the one from above?

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 6]
```diff
@@ -74,18 +77,17 @@ public async Task<IReadOnlyCollection<IAnalysisIssue>> Analyze(string filePath,
             await EnsureEslintBridgeClientIsInitialized(rulesProvider.GetActiveRulesConfiguration(), cancellationToken);
             var analysisResponse = await eslintBridgeClient.Analyze(filePath, tsConfig, cancellationToken);
 
+            if (analysisResponse.ParsingError != null &&
```
Comment (duncanp-sonar) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:80]: We've just called the method `EnsureEslintBridgeClientIsInitialized` above, so it's not obvious why we'd still need to explicitly handle "not initialized". I think it needs a comment here, and possibly in `EnsureEslintBridgeClientIsInitialized`.

File: src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs [hunk 7]
```diff
@@ -152,6 +152,75 @@ public async Task Analyze_EslintBridgeClientNotInitializedResponse_CallsInitLint
...
+                .ReturnsAsync(validResponse);
+
+            var convertedIssues = new[] { Mock.Of<IAnalysisIssue>() };
+            var issueConverter = new Mock<IEslintBridgeIssueConverter>();
+            SetupConvertedIssue(issueConverter, "some path", validResponse.Issues.First(), convertedIssues[0]);
+
+            var testSubject = CreateTestSubject(client.Object, issueConverter: issueConverter.Object);
+            var result = await testSubject.Analyze("some path", "some config", CancellationToken.None);
+
+            result.Should().BeEquivalentTo(convertedIssues);
```
Comment (duncanp-sonar) [inline src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs:203]: It wouldn't hurt to add some extra checks here e.g. that `analyze` is called twice, and that the "not initialized" message is not logged.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 5 above)
Comment (rita-sonarsource) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:83]: Good question. From this class' point of view, it shouldn't matter, but since we know that it's re-reading the file behind the scene, it'd be better to re-use the values. I'll change.

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs (hunk 6 above)
Comment (rita-sonarsource) [reply src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:80]: Originally I thought about calling 
```
RequireLinterUpdate();
await EnsureEslintBridgeClientIsInitialized();
```
But thought it would be more confusing. I'll change it to that since I see that this is more confusing :D

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 8]
```diff
@@ -71,22 +73,15 @@ internal sealed class EslintBridgeAnalyzer : IEslintBridgeAnalyzer
...
         {
-            try
-            {
-                return await GetFileIssues(filePath, tsConfig, cancellationToken);
-            }
-            catch (EslintBridgeClientNotInitializedException)
+            await EnsureEslintBridgeClientIsInitialized(cancellationToken);
+            var analysisResponse = await eslintBridgeClient.Analyze(filePath, tsConfig, cancellationToken);
+
+            if (LinterNotInitializedResponse(analysisResponse))
```
Comment (duncanp-sonar) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:79]: I still don't think it's obvious _why_ we might get a "not initialised" error having just called `EnsureEslintBridgeClientIsInitialized`. I think it needs a comment e.g.

```
// The call to `EnsureEslintBridgeClientIsInitialized` above doesn't guarantee the client is correctly initialized (e.g. the external process might have crashed).
// So we still need to handle the "not initialised" case here.
```
