### PR TITLE
Updated webclient to get fix for #2406

### LINKED ISSUE #2406: SonarQubeService.IsConnected should be false if a connection could not be established
### Description

It is expected that the call to SonarQubeService.ConnectAsync could fail e.g. because the server is not running or not reachable.
However, SonarQubeService.IsConnected should be false in that case.

### Repro steps

1. Connect a solution to a local SQ
2. Shutdown VS
3. Shutdown SQ
4. Open the solution in VS so one of the services calls "ConnectAsync".
The call to "ConnectAsync" will fail.

### Expected behavior

SonarQubeService.IsConnected should be false.

### Actual behavior

SonarQubeService.IsConnected is true.
This can cause failures in consuming components that check IsConnected before performing an operation e.g. #2287.

### Known workarounds

None.

### Related information

* SonarLint for VS Version: reported in v4.33 but definitely existed in earlier versions.
* SonarQube server version: n/a

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #2406 and #2287

### CODE REVIEW

File: src/Integration/MefServices/ActiveSolutionBoundTracker.cs [hunk 1]
```diff
@@ -127,9 +127,6 @@ private async Task UpdateConnectionAsync()
                 await Core.WebServiceHelper.SafeServiceCallAsync(() => sonarQubeService.ConnectAsync(connectionInformation,
                     CancellationToken.None), this.logger);
             }
-
-            Debug.Assert((boundProject != null) == sonarQubeService.IsConnected,
-                $"Inconsistent connection state: Solution bound={boundProject != null}, service connected={sonarQubeService.IsConnected}");
```
Comment (duncanp-sonar) [inline src/Integration/MefServices/ActiveSolutionBoundTracker.cs:132]: This assertion was incorrect; we do have binding information, but could not connect.

I've manually check the TaintPackage load bug doesn't repro, and didn't find any issues apart from this assertion.

The message logging for the other features (suppressions, taint issues etc) looks pretty good e.g. along the lines of "couldn't update suppressions - server is not connected".

**Review by rita-sonarsource — APPROVED** [review]
