### PR TITLE
Fix js/ts taint help links

### LINKED ISSUE #3119: Support taint help links
Following https://github.com/SonarSource/sonarlint-visualstudio/issues/2411 

JS/TS repo names on the java side: https://github.com/SonarSource/sonarlint-core/blob/bb9077fbfaaaf2bb51803ceee5c3bb89adf9c607/core/src/main/java/org/sonarsource/sonarlint/core/serverapi/issue/IssueApi.java#L52

### PR DESCRIPTION
**Pull request by rita-sonarsource**
Fixes  #3119

### CODE REVIEW

File: src/Core/SonarArtefactKeys.cs [hunk 1]
```diff
@@ -72,6 +72,9 @@ public static class SonarRuleRepoKeys
         public const string CSharpSecurityRules = "roslyn.sonaranalyzer.security.cs";
         public const string CSharpRules = "csharpsquid";
 
+        public const string JsSecurityRules = "jssecurity";
```
Comment (rita-sonarsource) [inline src/Core/SonarArtefactKeys.cs:75]: Java side: https://github.com/SonarSource/sonarlint-core/blob/bb9077fbfaaaf2bb51803ceee5c3bb89adf9c607/core/src/main/java/org/sonarsource/sonarlint/core/serverapi/issue/IssueApi.java#L52

**Review by ugras-ergun-sonarsource — APPROVED** [review]

**Review by duncanp-sonar — APPROVED** [review]
