### PR TITLE
Handle configuration manager being null

### LINKED ISSUE #661: SonarLint crashes VS when opening a legacy-bound solution
### Repro steps

1. Open VS
2. Open an existing C# solution: the solution I was using: [NetFwConsoleApp2017_VS2017Crash_SLVS4.1.zip](https://github.com/SonarSource/sonarlint-visualstudio/files/2080446/NetFwConsoleApp2017_VS2017Crash_SLVS4.1.zip)
.
### Expected behavior
VS opens correctly

### Actual behavior
VS UI locks up for a while then crashes.

### Call stack
Exception thrown on the main thread:
+		$exception	{"Value cannot be null.\r\nParameter name: source"}	System.ArgumentNullException

```
>	System.Core.dll!System.Linq.Enumerable.OfType<EnvDTE.Configuration>(System.Collections.IEnumerable source)	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.VsShellUtils.EnumerateProjectProperties(EnvDTE.Project project, string propertyName)	Unknown
 	System.Core.dll!System.Linq.Enumerable.WhereEnumerableIterator<EnvDTE.Property>.MoveNext()	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.SolutionRuleSetsInformationProvider.GetProjectRuleSetsDeclarations(EnvDTE.Project project)	Unknown
 	System.Core.dll!System.Linq.Buffer<SonarLint.VisualStudio.Integration.RuleSetDeclaration>.Buffer(System.Collections.Generic.IEnumerable<SonarLint.VisualStudio.Integration.RuleSetDeclaration> source)	Unknown
 	System.Core.dll!System.Linq.Enumerable.ToArray<SonarLint.VisualStudio.Integration.RuleSetDeclaration>(System.Collections.Generic.IEnumerable<SonarLint.VisualStudio.Integration.RuleSetDeclaration> source)	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.SolutionBindingInformationProvider.IsFullyBoundProject(System.Collections.Generic.Dictionary<string, Microsoft.VisualStudio.CodeAnalysis.RuleSets.RuleSet> cache, SonarLint.VisualStudio.Integration.NewConnectedMode.BindingConfiguration binding, EnvDTE.Project project)	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.SolutionBindingInformationProvider.GetUnboundProjects.AnonymousMethod__0(EnvDTE.Project p)	Unknown
 	System.Core.dll!System.Linq.Enumerable.CombinePredicates.AnonymousMethod__0(System.__Canon x)	Unknown
 	System.Core.dll!System.Linq.Enumerable.WhereEnumerableIterator<EnvDTE.Project>.MoveNext()	Unknown
 	System.Core.dll!System.Linq.Buffer<EnvDTE.Project>.Buffer(System.Collections.Generic.IEnumerable<EnvDTE.Project> source)	Unknown
 	System.Core.dll!System.Linq.Enumerable.ToArray<EnvDTE.Project>(System.Collections.Generic.IEnumerable<EnvDTE.Project> source)	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ErrorListInfoBarController.ProcessSolutionBindingCore()	Unknown
 	SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ErrorListInfoBarController.ProcessSolutionBinding()	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
```

### Known workarounds

None

### Related information

* SonarLint for VS Version: 4.1.0.03539
* Visual Studio Version: 2017 Ultimate v15.7.3
* Languages in your solution (C#, VB.Net, both NET Fx and NET Core)

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixed #661

### CODE REVIEW

File: src/Integration/Helpers/VsShellUtils.cs [hunk 1]
```diff
@@ -111,28 +111,29 @@ public static void ActivateSolutionExplorer(IServiceProvider serviceProvider)
...
             // Try to find the property on the project level properties (relevant for legacy web projects only)
             Property property = FindProperty(project.Properties, propertyName);
-            if (property == null)
+
+            if (property != null)
+            {
+                return new Property[] { property };
+            }
+
+            if (project.ConfigurationManager != null)
```
Comment (duncanp-sonar) [inline src/Integration/Helpers/VsShellUtils.cs]: The configuration manager can be null for some project types. I'm not sure why we haven't encountered this before (something may have changed in the platform).

File: src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs [hunk 2]
```diff
@@ -67,13 +64,15 @@ public string ProjectKind
 
         public PropertiesMock Properties
         {
-            get { return this.properties; }
-        }
+            get;
+        } = new PropertiesMock();
```
Comment (duncanp-sonar) [inline src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs]: Miscellaneous - changed a couple of properties to auto-properties
