### PR TITLE
Fix #790 - imported ruleset not detected

### LINKED ISSUE #658: SonarLint for Visual Studio 2017 plugin does not respect shared imports
[SonarLint for Visual Studio 2017](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017) does not work well with shared imports.

I am using [Directory.Build.props](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/master/Directory.Build.props) to import many code analyzers to all projects.
A custom .ruleset file is also specified [there](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/84471ff5afaa3ecc19bc5d99b99c70c5b6f8e55c/Directory.Build.props#L4).
[Here](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/84471ff5afaa3ecc19bc5d99b99c70c5b6f8e55c/CodingRules.ruleset#L4) I am importing the other .ruleset generated by the SonarLint plugin.

SonarLint VS plugin does not recognize these shared imports.
When I click on Update in 'Test Explorer - Sonar Qube' window, it always creates needles rulesets for each projects. For example: \ClassLibrary1\ClassLibrary1.ruleset.
It also inserts needless PropertyGroups to .csproj files like

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet>ClassLibrary1.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet>ClassLibrary1.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```

Note: I removed .sonarlint\TestSonarlint.slconfig from the example repository because it has some confidential information.

### LINKED ISSUE #790: SLVS incorrectly complains that projects are not bound
### Description

When a bound solution is opened, SLVS raises a warning if any supported project (i.e. C#, VB) in the solution does not reference the generated-solution level ruleset.

However, it raises the warning incorrectly in a number of cases:
1. The project references a ruleset that _includes_ the generated ruleset, but the _RuleSetInclude_ contains forward-slash path separators, or the relative path starts with ".\"
2. The ruleset is directly referenced by the project
3. [WON'T FIX] The ruleset is referenced indirectly by through nested ruleset includes i.e. project references ruleset _A_ which includes ruleset _B_ which includes the generated ruleset.

### Repro steps

See the files in the #658: _SonarLint for Visual Studio 2017 plugin does not respect shared imports_
for examples files for case (1).

### Related information

* SonarLint for VS Version: up and including to 4.7
* Languages affected: C#, VB.Net

### PR DESCRIPTION
**Pull request by duncanp-sonar**

### CODE REVIEW

File: src/Integration.UnitTests/Helpers/RuleSetHelperTests.cs [hunk 1]
```diff
@@ -130,55 +130,6 @@ public void RuleSetHelper_UpdateExistingProjectRuleSet()
             RuleSetAssert.AreEqual(expectedRuleSet, existingProjectRuleSet, "Update should delete previous solution rulesets, and replace them with a new one provide");
         }
 
-        [TestMethod]
-        public void RuleSetHelper_FindInclude_ArgChecks()
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/Helpers/RuleSetHelperTests.cs]: I moved the code for handling _RuleSetIncludes_ into a separate class, so all of the related tests are now in a separate class.

File: src/Integration/Helpers/RuleSetHelper.cs [hunk 2]
```diff
@@ -75,48 +74,6 @@ public static IEnumerable<RuleSetInclude> FindAllIncludesUnderRoot(RuleSet ruleS
...
-
-            if (target == null)
-            {
-                throw new ArgumentNullException(nameof(target));
-            }
-
-            string relativeTargetFilePath = PathHelper.CalculateRelativePath(source.FilePath, target.FilePath);
-
-            var matchingRuleSetIncludes = source.RuleSetIncludes.Where(i =>
-                StringComparer.OrdinalIgnoreCase.Equals(i.FilePath, relativeTargetFilePath)
```
Comment (duncanp-sonar) [inline src/Integration/Helpers/RuleSetHelper.cs]: The old code didn't handle complex relative paths or alternative path separators.
I've fixed this is in the new code by converting relative paths to absolute paths in a canonical form.

File: src/Integration/LocalServices/SolutionBindingInformationProvider.cs [hunk 3]
```diff
@@ -31,6 +31,7 @@ namespace SonarLint.VisualStudio.Integration
     internal class SolutionBindingInformationProvider : ISolutionBindingInformationProvider
     {
         private readonly IServiceProvider serviceProvider;
+        private readonly ISolutionRuleSetsInformationProvider ruleSetInfoProvider;
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/SolutionBindingInformationProvider.cs]: Simplification: the _ruleSetInfoProvider_ service was fetched from three separate places in the code, and was also re-fetched for each project when looping through the list of projects. I've changed it to be fetched once and stored.

File: src/Integration/LocalServices/SolutionBindingInformationProvider.cs [hunk 4]
```diff
@@ -71,78 +75,58 @@ private IEnumerable<Project> GetUnboundProjects(BindingConfiguration binding)
...
 
+            var rulesetSerializer = this.serviceProvider.GetService<IRuleSetSerializer>();
+            rulesetSerializer.AssertLocalServiceIsNotNull();
+
             // Projects will be using the same solution ruleset in most of the cases,
             // projects could have multiple configurations all of which using the same rule set,
             // we want to minimize the number of disk operations since the
             // method can be called from the UI thread, hence this short-lived cache
-            Dictionary<string, RuleSet> cache = new Dictionary<string, RuleSet>(StringComparer.OrdinalIgnoreCase);
+            var cachingSerializer = new CachingRulesetSerializer(rulesetSerializer);
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/SolutionBindingInformationProvider.cs]: Simplification: factored out the caching into a private decorator class.

File: src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs [hunk 5]
```diff
@@ -78,29 +78,31 @@ private IEnumerable<RuleSetDeclaration> GetProjectRuleSetsDeclarationsIterator(P
              * for C# and VB projects that use the new project system).
              */
 
-            bool found = false;
+            var declarations = new List<RuleSetDeclaration>();
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs]: Simplification: using _yield_ didn't add anything here all and made debugging harder.

File: src/Integration/Helpers/RuleSetHelper.cs [hunk 6]
```diff
@@ -75,48 +74,6 @@ public static IEnumerable<RuleSetInclude> FindAllIncludesUnderRoot(RuleSet ruleS
                                             });
         }
 
-        /// <summary>
```
[the remark this answers is not in the document]
Comment (duncanp-sonar) [reply src/Integration/Helpers/RuleSetHelper.cs]: This _RuleSetHelper_ class now only contains methods that update a ruleset. I'll rename it (and the corresponding test class) to _RuleSetUpdater_. I didn't do it as part of this commit as sometimes GitHub doesn't display files that have been both edited and renamed in way that is easy to review.
