### PR TITLE
Don't try to fetch ruleset path when CodeAnalysisProperty is null or whitespace

### LINKED ISSUE #1532: Binding fails for new-style SDK C# projects when ruleset property is set to a whitespace
### Description

When binding a solution with a c# project that has <CodeAnalysisRuleSet> property set to a whitespace, binding fails and an error is shown in SonarLint pane:
```
Establishing new binding...
Binding solution to SonarQube project: Started
Binding solution to SonarQube project: Discovering solution projects
   Included projects:
   * REMOVED PROJECTS HERE
   Excluded projects:
   * REMOVED PROJECTS HERE

   You can change the exclusion options via the SonarLint project-level context menu i.e. Solution Explorer -> Select project(s)
Binding solution to SonarQube project: Download quality profile(s):
   Successfully downloaded quality profile. Name: REMOVED, Key: REMOVED, Language: 'C++'
   Successfully downloaded quality profile. Name: REMOVED, Key: REMOVED, Language: 'C'
   Successfully downloaded quality profile. Name: REMOVED, Key: REMOVED, Language: 'C#'
INFO: SonarLint connected mode no longer installs the analyzers NuGet packages. The analyzers embedded in the VSIX are used instead.
Binding solution to SonarQube project: Generating project rule sets
Ruleset binding: initial binding. All projects need to be updated to reference the generated ruleset.
Project-level binding is not required for project 'REMOVED'
Project-level binding is not required for project 'REMOVED'
...
Project-level binding is not required for project 'REMOVED'
Project-level binding is not required for project 'REMOVED'
Unexpected error during workflow execution: Value cannot be null.
Parameter name: relativePath.
```

### Notes
Reported directly by a customer who then left the company he was working at -> we don't have any further information about the bug.
* Seems like the error comes from `PathHelper.ResolveRelativePath`, as that's the only place that throws argument null exception for an argument named "relativePath", which is used only for ruleset calculations -- hence, the problem is likely with a C# binding.
* Based on log message "Ruleset binding: initial binding" -- we are in the process of first time binding.
* Based on log message "Project-level binding is not required for project" -- we are in the process of calling IProjectBinder.IsBindingRequired by IUnboundProjectFinder.GetUnboundProjects.

### Repro steps

1. Create new-style SDK project
2. Set CodeAnalysisRuleSet to a whitespace, e.g. a space `<CodeAnalysisRuleSet> </CodeAnalysisRuleSet>` or empty line
```
<CodeAnalysisRuleSet>
		
</CodeAnalysisRuleSet>
```

### Expected behavior

Binding succeeded. 

### Actual behavior

Binding failed.

### Known workarounds

Remove the whitespace, e.g. `<CodeAnalysisRuleSet></CodeAnalysisRuleSet>`

### Related information

SonarLint for Visual Studio 2017 Version: 4.22.0.18519
Visual Studio 2017 Version 15.9.21
Languages in your solution: C# and C++

### PR DESCRIPTION
**Pull request by rita-g-sonarsource**
Fixes #1532

### CODE REVIEW

File: src/Integration/Binding/RuleSetReferenceChecker.cs [hunk 1]
```diff
@@ -50,6 +54,10 @@ public bool IsReferencedByAllDeclarations(Project project, string targetRuleSetF
         {
             var declarations = ruleSetInfoProvider.GetProjectRuleSetsDeclarations(project).ToArray();
 
+            logger.WriteLine(Strings.Bind_ProjectRulesetDeclarations,
```
Comment (rita-g-sonarsource) [inline src/Integration/Binding/RuleSetReferenceChecker.cs:57]: Log for future troubleshooting

File: src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs [hunk 2]
```diff
@@ -128,7 +128,13 @@ public string GetSolutionSonarQubeRulesFolder(SonarLintMode bindingMode)
 
         public bool TryGetProjectRuleSetFilePath(RuleSetDeclaration declaration, out string fullFilePath)
         {
-            List<string> options = new List<string>();
+            if (string.IsNullOrWhiteSpace(declaration.RuleSetPath))
```
Comment (rita-g-sonarsource) [inline src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs:131]: This is the fix

File: src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs [hunk 3]
```diff
@@ -206,47 +206,66 @@ public void SolutionRuleSetsInformationProvider_GetSolutionSonarQubeRulesFolder_
         }
 
         [TestMethod]
-        public void SolutionRuleSetsInformationProvider_TryGetProjectRuleSetFilePath()
```
Comment (rita-g-sonarsource) [inline src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs:209]: Split this test into the 3 cases that were commented

File: src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs [hunk 4]
```diff
@@ -206,47 +206,66 @@ public void SolutionRuleSetsInformationProvider_GetSolutionSonarQubeRulesFolder_
...
+        }
 
-            // Case 3: File doesn't exist
-            foreach (var filePath in fileSystem.AllFiles)
-            {
-                fileSystem.RemoveFile(filePath);
-            }
-            declaration = CreateDeclaration(project, "MyFile.ruleset");
+        [TestMethod]
+        public void TryGetProjectRuleSetFilePath_DeclarationReferencesNonExistingFile_NullReturned()
```
Comment (rita-g-sonarsource) [inline src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs:241]: Regression test

File: src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs [hunk 5]
```diff
@@ -206,47 +206,66 @@ public void SolutionRuleSetsInformationProvider_GetSolutionSonarQubeRulesFolder_
...
+            // Assert
+            ruleSetPath.Should().BeNull();
+        }
+
+        [TestMethod]
+        [DataRow(null)]
+        [DataRow("")]
+        [DataRow(" ")]
+        [DataRow("\n\r")]
+        public void TryGetProjectRuleSetFilePath_DeclarationReferencesEmptyPath_NullReturned(string filePath)
```
Comment (rita-g-sonarsource) [inline src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs:260]: Regression test
