### PR TITLE
Fix the help link for taint issues

### LINKED ISSUE #2102: Fix help link of Taint issues in secondary locations panel
#### Description

When a taint issue with secondary locations is selected, the secondary locations panel contains a help link to rules.sonarsource.com. The link however is invalid and leads to an error page (e.g. `https://rules.sonarsource.com/roslyn.sonaranalyzer.security.cs/RSPEC-2076`).

Steps to reproduce:
1. Select a taint issue
2. In the SL panel click on the help link (in the issue description).
Expected ==> correct link is opened.
Actual ==> link leads to an error page.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #2102

### CODE REVIEW

File: src/Core.UnitTests/RuleHelpLinkProviderTests.cs [hunk 1]
```diff
@@ -30,8 +30,11 @@ public class RuleHelpLinkProviderTests
         [DataRow("javascript:123", "https://rules.sonarsource.com/javascript/RSPEC-123")]
         [DataRow("javascript:SOMETHING", "https://rules.sonarsource.com/javascript/RSPEC-SOMETHING")]
         [DataRow("c:456", "https://rules.sonarsource.com/c/RSPEC-456")]
-        [DataRow("cpp:789", "https://rules.sonarsource.com/cpp/RSPEC-789")]
+        [DataRow("c:NonEmptyCaseWithoutBreak", "https://rules.sonarsource.com/c/RSPEC-NonEmptyCaseWithoutBreak")]
+        [DataRow("cpp:PPIncludeNonStandardCharacters", "https://rules.sonarsource.com/cpp/RSPEC-PPIncludeNonStandardCharacters")]
         [DataRow("php:101112", "https://rules.sonarsource.com/php/RSPEC-101112")]
+        [DataRow("roslyn.sonaranalyzer.security.cs:S2076", "https://rules.sonarsource.com/csharp/RSPEC-2076")]
```
Comment (duncanp-sonar) [inline src/Core.UnitTests/RuleHelpLinkProviderTests.cs:36]: Line 36 is the regression test case. I tweak a couple of the existing C/C++ examples to use real legacy rule names.

**Review by rita-g-sonarsource — APPROVED** [review]
