### PR TITLE
Change JS rule key to include repo id

### LINKED ISSUE #2301: JS issues do not have a help link
#### Description

JS issues from eslint-bridge do not have a help link.
An exception is thrown when attempting to calculate the rule's repository:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Length cannot be less than zero.
Parameter name: length
  Source=mscorlib
  StackTrace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at SonarLint.VisualStudio.Core.RuleHelpLinkProvider.GetHelpLink(String ruleKey) in C:\Projects\sonarlint-visualstudio\src\Core\RuleHelpLinkProvider.cs:line 46
   at SonarLint.VisualStudio.Integration.Vsix.IssuesSnapshot.TryGetValue(Int32 index, String keyName, Object& content) in C:\Projects\sonarlint-visualstudio\src\Integration.Vsix\ErrorList\IssuesSnapshot.cs:line 218
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.SnapshotTableEntryViewModel.TryGetValue(String columnName, Object& content)

  This exception was originally thrown at this call stack:
    string.Substring(int, int)
    SonarLint.VisualStudio.Core.RuleHelpLinkProvider.GetHelpLink(string) in RuleHelpLinkProvider.cs
    SonarLint.VisualStudio.Integration.Vsix.IssuesSnapshot.TryGetValue(int, string, out object) in IssuesSnapshot.cs
    Microsoft.VisualStudio.Shell.TableControl.Implementation.SnapshotTableEntryViewModel.TryGetValue(string, out object)
```

image

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes the bug calculating the help link

Fixes #2301

### CODE REVIEW

File: src/TypeScript/Rules/RulesRepository.cs [hunk 1]
```diff
@@ -72,24 +71,8 @@ public RulesRepository([Import(RuleDefinitionsFilePathContractName)] string type
             .ToList()
             .AsReadOnly();
 
-        private static string GetRuleKey(string eslintRuleKey, IEnumerable<RuleDefinition> rules)
-        {
-            var repoAndKey = rules.FirstOrDefault(x => eslintRuleKey.Equals(x.EslintKey, System.StringComparison.OrdinalIgnoreCase))
+        private static string GetRuleKey(string eslintRuleKey, IEnumerable<RuleDefinition> rules) =>
+            rules.FirstOrDefault(x => eslintRuleKey.Equals(x.EslintKey, System.StringComparison.OrdinalIgnoreCase))
                 ?.RuleKey;
-            return repoAndKey == null ? null : StripRepoPrefix(repoAndKey);
```
Comment (duncanp-sonar) [inline src/TypeScript/Rules/RulesRepository.cs:79]: Out of interest, I started looking at adding `RepoId` as a separate field to `IAnalysisIssue`, expecting it to create a lot of changes.
Unfortunately, it did so I went for the simpler fix of changing the JS rule key to be e.g. `javascript:S123`.

Ticket #2291 ("standardise rule keys") is still open.

**Review by rita-sonarsource — APPROVED** [review]
