### PR TITLE
Fix KnownUIContextsWrapper pass-through

### LINKED ISSUE #2742: [VS2022] Cannot bind to "normal" solutions
### Description

Cannot bind to non-"open as folder" solutions.

### Repro steps

Attempt to bind to a "normal" solution e.g. https://github.com/SonarSource/sonarlint-visualstudio-sampleprojects, `standalone\vs2022\NormalSolution`.

image

### Expected behavior

Solution is bound succesfully.

### Actual behavior

The "bind" button is disabled.

### Known workarounds

None

### Related information

* SonarLint for VS Version: v5.0
* Visual Studio Version: VS2022
* SonarQube server version: n/a
* Languages in your solution: C#, VB.Net, Javascript, C, C++ (VCX proj)

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fix #2742

### CODE REVIEW

File: src/Integration/Helpers/KnownUIContextsWrapper.cs [hunk 1]
```diff
@@ -91,7 +91,7 @@ public class KnownUIContextsWrapper : IKnownUIContexts
 
         public IUIContext SolutionExistsAndFullyLoadedContext => new UIContextWrapper(KnownUIContexts.SolutionExistsAndFullyLoadedContext);
 
-        public IUIContext SolutionExistsAndNotBuildingAndNotDebuggingContext => new UIContextWrapper(KnownUIContexts.SolutionBuildingContext);
+        public IUIContext SolutionExistsAndNotBuildingAndNotDebuggingContext => new UIContextWrapper(KnownUIContexts.SolutionExistsAndNotBuildingAndNotDebuggingContext);
```
Comment (duncanp-sonar) [inline src/Integration/Helpers/KnownUIContextsWrapper.cs:94]: Copy-and-paste error that prevented the "bind" command from being enabled.

We don't have any test for this wrapper, and it wouldn't be easy to add them.

**Review by rita-sonarsource — APPROVED** [review]
