### PR TITLE
Fix removing already removed config scope

### LINKED ISSUE #5310: Do not send remove config scope when it's not set

### PR DESCRIPTION
**Pull request by georgii-borovinskikh-sonarsource**
Fixes #5310

### CODE REVIEW

File: src/SLCore/State/ActiveConfigScopeTracker.cs [hunk 1]
```diff
@@ -131,7 +131,10 @@ public void RemoveCurrentConfigScope()
 
         using (asyncLock.Acquire())
         {
-            Debug.Assert(currentConfigScope != null);
+            if (currentConfigScope is null)
```
Comment (georgii-borovinskikh-sonarsource) [inline src/SLCore/State/ActiveConfigScopeTracker.cs:134]: I can't do anything about remove being called multiple times, so it's best to just ignore it

**Review by ugras-ergun-sonarsource — APPROVED** [review]
