### PR TITLE
Handle exceptions in quick fix source 

### LINKED ISSUE #3227: VS crashes due to unhanded exception with quick fixes
### Description

Random exception that occurred when debugging and crashed VS:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SonarLint.VisualStudio.Infrastructure.VS
  StackTrace:
   at SonarLint.VisualStudio.Infrastructure.VS.RunOnUIThread.<RunAsync>d__1.MoveNext() in C:\projects\sonarlint-visualstudio\src\Infrastructure.VS\RunOnUIThread.cs:line 64
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.<RunOnUIThread>d__3.MoveNext() in C:\projects\sonarlint-visualstudio\src\Infrastructure.VS\ThreadHandling.cs:line 45
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SonarLint.VisualStudio.IssueVisualization.Editor.QuickActions.QuickFixes.QuickFixActionsSource.<TagAggregator_TagsChanged>d__16.MoveNext() in C:\projects\sonarlint-visualstudio\src\IssueViz\Editor\QuickActions\QuickFixes\QuickFixActionsSource.cs:line 146

  This exception was originally thrown at this call stack:
    SonarLint.VisualStudio.Infrastructure.VS.RunOnUIThread.RunAsync(System.Action) in RunOnUIThread.cs
    [External Code]
    SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.RunOnUIThread(System.Action) in ThreadHandling.cs
    [External Code]
    SonarLint.VisualStudio.IssueVisualization.Editor.QuickActions.QuickFixes.QuickFixActionsSource.TagAggregator_TagsChanged(object, Microsoft.VisualStudio.Text.Tagging.TagsChangedEventArgs) in QuickFixActionsSource.cs
```

Regardless of the reason for this exception, it should not crash VS.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #3227

### CODE REVIEW

File: src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs [hunk 1]
```diff
@@ -141,11 +143,21 @@ public void Dispose()
             issueLocationsTagAggregator.Dispose();
         }
 
-        private async void TagAggregator_TagsChanged(object sender, TagsChangedEventArgs e)
```
Comment (duncanp-sonar) [inline src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs:144]: FYI VSTHRD100 warns about `async void` methods - we have eight other occurrences.
Fixing those is covered by #3171, although we might decide to break that down into separate tickets when we start working on it.

**Review by rita-sonarsource — APPROVED** [review]
