### PR TITLE
Fixed #369 - not disconnecting on solution close

### LINKED ISSUE #369: Closing a solution does not disconnect from the SQ server unless the TE is open
Closing a bound solution should disconnect from the currently connected SQ server.
However, it only does this if the Team Explorer SQ pane been opened at some point during the VS session.

Repo:
1. Open VS but don`t have the Team Explorer window open at start up (you might need to close the TE window and restart VS)
2. Open a bound solution
3. Close the bound solution

4. Re-open the solution

**Expected:**
The connection to the SQ server is closed at step 3 and a new connection is made at step 4

**Actual:**
The connection to the SQ server is not closed at step 3. Attempting to connect at step 4 produces an error in the output window _("SonarQube request failed: This operation expects the service not to be connected. ")_

### PR DESCRIPTION
**Pull request by duncanp-sonar**
The fix is simple: the slow part was adding the tests.

BTW I noticed that the ErrorListBarController is also directly calling _this.host.ActiveSection.DisconnectCommand_. I'll send a separate PR for that.

### CODE REVIEW

File: src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs [hunk 1]
```diff
@@ -156,25 +170,9 @@ public void ActiveSolutionBoundTracker_Changes()
...
             var boundProject = new BoundSonarQubeProject(new Uri("http://localhost:9000"), "key");
 
-            var solutionBinding = new ConfigurableSolutionBindingSerializer();
-
-            bool serviceIsConnected = false;
-            var mockSqService = new Mock<ISonarQubeService>();
-
-            Expression<Func<ISonarQubeService, Task>> connectMethod = x => x.ConnectAsync(It.IsAny<ConnectionInformation>(), It.IsAny<CancellationToken>());
-            Expression<Action<ISonarQubeService>> disconnectMethod = x => x.Disconnect();
+            SetupService(isConnected: false);
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs]: I've added a couple of setup helper methods that hide some of the unpleasantness around setting up all of the mocks correctly.

File: src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs [hunk 2]
```diff
@@ -261,24 +252,188 @@ public void ActiveSolutionBoundTracker_Changes()
...
+
+        [TestMethod]
+        public void UpdateConnection_WasDisconnected_NewSolutionIsUnbound_NoConnectOrDisconnectCalls()
+        {
+            // Arrange
+            var testSubject = new ActiveSolutionBoundTracker(this.host, this.activeSolutionTracker, sonarLintOutputMock.Object);
+
+            // Act
+            SetupService(isConnected: false);
+            SetSolutionBinding(null);
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs]: Strictly these two _setup_ calls are part of _Arrange_ rather than _Act_. I'll move them.
