### PR TITLE
[PERF] Fix gold bar when checking for unbound projects

### LINKED ISSUE #2791: Checking for unbound solutions causes VS to be unresponsive
### Description

Re-opening a large bound solution can cause VS to display to become unresponsive and display a gold bar.

### Repro steps

Re-open a large bound solution e.g.

1. Clone the MS Roslyn repo
2. Open in VS and bind to SC/SQ
3. Close VS
4. Open the project in VS again and wait

Note: the gold bar does not appear every time

### Expected result

No gold bar.

### Actual result

VS displays a gold bar complaining about SLVS.

![image](https://user-images.githubusercontent.com/10757559/143448689-7b4421ff-2797-444e-9d2d-cdc354abe0ca.png)

#### PerfView extract

In this case, VS was blocked for seven seconds during the checks to see whether the bound projects were up to date.

```
Name                                 	 Inc %	     Inc	Inc Ct	Exc %	Exc	Exc Ct	Fold	Fold Ct	                             When
+ Process64 devenv (63284) Args:     	 100.0	7,288.122	 4,604	  0.0	  0	     0	   0	      0	 9A99999AA999A9A999A999999999A999
 + Thread (1708) CPU=8313ms (VS Main)	 100.0	7,288.122	 4,604	  0.0	  0	     0	   0	      0	 9A99999AA999A9A999A999999999A999
  + ntdll!?                          	  99.3	7,235.140	 4,470	  0.0	  0	     0	   0	      0	 99999999999999999999999999999999

...

Name                                                                                                                                                                                                              	Inc %	     Inc	Inc Ct	Exc %	Exc	Exc Ct	Fold	Fold Ct	                             When
  |        + SonarLint.VisualStudio.Integration!ErrorListInfoBarController.ProcessSolutionBinding                                                                                                                 	 99.3	7,235.140	 4,470	  0.0	   	      	    	       	 99999999999999999999999999999999
  |         + SonarLint.VisualStudio.Integration!ErrorListInfoBarController.ProcessSolutionBindingCore                                                                                                            	 99.3	7,233.725	 4,467	  0.0	   	      	    	       	 99999999999999999999999999999999
  |         |+ SonarLint.VisualStudio.Integration!UnboundProjectFinder.GetUnboundProjects                                                                                                                         	 98.4	7,170.365	 4,281	  0.0	   	      	    	       	 99999999999999999999999999999997
  |         ||+ SonarLint.VisualStudio.Integration!UnboundProjectFinder.GetUnboundProjects                                                                                                                        	 98.4	7,169.088	 4,277	  0.0	   	      	    	       	 99999999999999999999999999999997
  |         |||+ system.core.ni!?                                                                                                                                                                                 	 98.3	7,166.088	 4,274	  0.0	   	      	    	       	 99999999999999999999999999999997
  |         ||||+ SonarLint.VisualStudio.Integration!SonarLint.VisualStudio.Integration.UnboundProjectFinder+<>c__DisplayClass6_0.<GetUnboundProjects>b__0(class EnvDTE.Project)                                  	 97.5	7,109.041	 4,098	  0.0	   	      	    	       	 79999999999999999999999999999997
  |         |||||+ SonarLint.VisualStudio.Integration!CSharpVBProjectBinder.IsBindingRequired                                                                                                                     	 97.5	7,104.708	 4,088	  0.0	   	      	    	       	 79999999999999999999999999999997
  |         ||||||+ system.core.ni!?                                                                                                                                                                              	 97.5	7,103.708	 4,087	  0.0	   	      	    	       	 79999999999999999999999999999997
  |         |||||||+ SonarLint.VisualStudio.Integration!SonarLint.VisualStudio.Integration.Binding.CSharpVBProjectBinder+<>c__DisplayClass12_0.<IsBindingRequired>b__1(class SonarLint.VisualStudio.Core.Language)	 97.5	7,103.460	 4,086	  0.0	   	      	    	       	 79999999999999999999999999999997
  |         ||||||||+ SonarLint.VisualStudio.Integration!CSharpVBProjectBinder.IsFullyBoundProject                                                                                                                	 97.5	7,103.460	 4,086	  0.0	   	      	    	       	 79999999999999999999999999999997
  |         |||||||| + SonarLint.VisualStudio.Integration!RuleSetReferenceChecker.IsReferencedByAllDeclarations                                                                                                   	 94.1	6,854.673	 3,270	  0.0	   	      	    	       	 59999999999999999999999999999997
  |         |||||||| |+ SonarLint.VisualStudio.Integration!SolutionRuleSetsInformationProvider.GetProjectRuleSetsDeclarations                                                                                     	 89.0	6,485.563	 1,824	  0.0	   	      	    	       	 59998999998999999899989886889986
  |         |||||||| ||+ SonarLint.VisualStudio.Integration!SolutionRuleSetsInformationProvider.GetProjectRuleSetsDeclarationsIterator                                                                            	 89.0	6,485.563	 1,824	  0.0	   	      	    	       	 59998999998999999899989886889986
  |         |||||||| || + SonarLint.VisualStudio.Integration!VsShellUtils.GetProjectProperties                                                                                                                    	 85.5	6,231.150	   965	  0.0	   	      	    	       	 58898899898988888889888886888886
  |         |||||||| || |+ system.core.ni!?                                                                                                                                                                       	 85.3	6,218.110	   945	  0.0	   	      	    	       	 58898899898988888889888886888886
  |         |||||||| || ||+ mscorlib.ni!?                                                                                                                                                                         	 85.0	6,197.961	   904	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || |||+ system.core.ni!?                                                                                                                                                                     	 85.0	6,197.961	   904	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || ||| + SonarLint.VisualStudio.Integration!SonarLint.VisualStudio.Integration.VsShellUtils+<>c__DisplayClass4_0.<GetProjectProperties>b__0(class EnvDTE.Configuration)                      	 85.0	6,196.803	   897	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || ||| |+ microsoft.visualstudio.interop.ni!?                                                                                                                                                	 84.7	6,172.548	   802	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || ||| ||+ msenv!?                                                                                                                                                                           	 84.7	6,171.454	   800	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || ||| |||+ clr!?                                                                                                                                                                            	 84.4	6,149.346	   765	  0.0	   	      	    	       	 58898889898988888889888885888886
  |         |||||||| || ||| ||||+ microsoft.visualstudio.interop.ni!?                                                                                                                                             	 82.6	6,020.725	   590	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| |||||+ microsoft.visualstudio.projectsystem.vs.implementation.ni!?                                                                                                                    	 82.6	6,018.808	   588	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||+ microsoft.visualstudio.projectsystem.vs.ni!?                                                                                                                                  	 82.6	6,018.808	   588	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| |||||| + microsoft.visualstudio.projectsystem.implementation!ProjectMultiThreadedService.ExecuteSynchronously                                                                         	 82.6	6,018.808	   588	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||  + microsoft.visualstudio.projectsystem.vs.ni!?                                                                                                                                	 82.6	6,018.808	   588	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||   + microsoft.visualstudio.projectsystem.vs.implementation.ni!?                                                                                                                	 82.6	6,018.626	   587	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||   |+ microsoft.visualstudio.threading.ni!?                                                                                                                                     	 82.2	5,993.113	   542	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||   ||+ mscorlib.ni!?                                                                                                                                                            	 82.2	5,990.722	   529	  0.0	   	      	    	       	 18898889897988888889888785788876
  |         |||||||| || ||| ||||||   |||+ clr!?                                                                                                                                                                   	 81.5	5,942.273	   421	  0.0	   	      	    	       	 18898889897988888789888775788876
  |         |||||||| || ||| ||||||   ||||+ microsoft.visualstudio.threading.ni!?                                                                                                                                  	 80.2	5,848.351	   317	  0.0	   	      	    	       	 18898889897988888787688775788876
  |         |||||||| || ||| ||||||   |||||+ kernelbase!?                                                                                                                                                          	 80.2	5,848.351	   317	  0.0	   	      	    	       	 18898889897988888787688775788876
  |         |||||||| || ||| ||||||   ||||| + ntdll!?                                                                                                                                                              	 80.2	5,848.351	   317	  0.0	   	      	    	       	 18898889897988888787688775788876
  |         |||||||| || ||| ||||||   |||||  + ntoskrnl!?                                                                                                                                                          	 80.2	5,848.351	   317	  0.0	   	      	    	       	 18898889897988888787688775788876
  |         |||||||| || ||| ||||||   |||||   + BLOCKED_TIME                                                                                                                                                       	 79.7	5,811.011	   158	 79.7	   	      	    	       	 18898889887988888787688775788876
  |         |||||||| || ||| ||||||   |||||   + CPU_TIME                                                                                                                                                           	  0.5	  37.340	   159	  0.5	   	      	    	       	 _ooooooooooooooooooooooooooooooo

```

```
Event Name                          	 Time MSec	Process Name  	Rest  
sonarlint/UnboundProjectFinder/Start	22,368.677	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	22,449.188	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" projectName="RoslynDeployment" 
sonarlint/ProjectBinderEnd          	22,749.205	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	22,749.271	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis" 
sonarlint/ProjectBinderEnd          	22,978.997	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	22,979.037	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="VBCSCompiler" 
sonarlint/ProjectBinderEnd          	23,051.007	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
sonarlint/ProjectBinder/Start       	23,051.037	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" projectName="csc" 
sonarlint/ProjectBinderEnd          	23,124.662	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" 
sonarlint/ProjectBinder/Start       	23,124.728	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" projectName="Microsoft.CodeAnalysis.CSharp" 
sonarlint/ProjectBinderEnd          	23,257.067	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" 
sonarlint/ProjectBinder/Start       	23,257.099	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" projectName="Microsoft.CodeAnalysis.VisualBasic" 
sonarlint/ProjectBinderEnd          	23,407.787	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	23,407.816	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.Workspaces" 
sonarlint/ProjectBinderEnd          	23,639.358	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	23,639.390	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="CompilersBoundTreeGenerator" 
sonarlint/ProjectBinderEnd          	23,698.501	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	23,698.529	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="CSharpErrorFactsGenerator" 
sonarlint/ProjectBinderEnd          	23,755.706	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" 
sonarlint/ProjectBinder/Start       	23,755.735	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" projectName="CSharpSyntaxGenerator" 
sonarlint/ProjectBinderEnd          	23,911.171	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" 
sonarlint/ProjectBinder/Start       	23,911.216	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" projectName="VisualBasicSyntaxGenerator" 
sonarlint/ProjectBinderEnd          	23,969.090	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" 
sonarlint/ProjectBinder/Start       	23,969.111	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" projectName="VisualBasicErrorFactsGenerator" 
sonarlint/ProjectBinderEnd          	24,030.223	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	24,030.246	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.Workspaces.Desktop" 
sonarlint/ProjectBinderEnd          	24,090.412	devenv (13612)	ThreadID="22,064" ProcessorNumber="9" 
sonarlint/ProjectBinder/Start       	24,090.442	devenv (13612)	ThreadID="22,064" ProcessorNumber="9" projectName="Microsoft.CodeAnalysis.Workspaces.MSBuild" 
sonarlint/ProjectBinderEnd          	24,162.341	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" 
sonarlint/ProjectBinder/Start       	24,162.369	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" projectName="Microsoft.CodeAnalysis.CSharp.Workspaces" 
sonarlint/ProjectBinderEnd          	24,258.828	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" 
sonarlint/ProjectBinder/Start       	24,258.866	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" projectName="Microsoft.CodeAnalysis.VisualBasic.Workspaces" 
sonarlint/ProjectBinderEnd          	24,355.207	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" 
sonarlint/ProjectBinder/Start       	24,355.237	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" projectName="Microsoft.CodeAnalysis.VisualBasic.Features" 
sonarlint/ProjectBinderEnd          	24,491.077	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	24,491.110	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.CSharp.Features" 
sonarlint/ProjectBinderEnd          	24,647.514	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	24,647.565	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.Features" 
sonarlint/ProjectBinderEnd          	24,883.580	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" 
sonarlint/ProjectBinder/Start       	24,883.613	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" projectName="Microsoft.CodeAnalysis.EditorFeatures.Text" 
sonarlint/ProjectBinderEnd          	24,940.044	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" 
sonarlint/ProjectBinder/Start       	24,940.078	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" projectName="Microsoft.CodeAnalysis.VisualBasic.EditorFeatures" 
sonarlint/ProjectBinderEnd          	25,000.782	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	25,000.808	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.CSharp.EditorFeatures" 
sonarlint/ProjectBinderEnd          	25,055.886	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	25,055.907	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.EditorFeatures" 
sonarlint/ProjectBinderEnd          	25,134.351	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	25,134.371	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.VisualBasic.Scripting" 
sonarlint/ProjectBinderEnd          	25,178.480	devenv (13612)	ThreadID="22,064" ProcessorNumber="12" 
sonarlint/ProjectBinder/Start       	25,178.501	devenv (13612)	ThreadID="22,064" ProcessorNumber="12" projectName="Microsoft.CodeAnalysis.Scripting" 
sonarlint/ProjectBinderEnd          	25,225.872	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" 
sonarlint/ProjectBinder/Start       	25,225.893	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" projectName="Microsoft.CodeAnalysis.CSharp.Scripting" 
sonarlint/ProjectBinderEnd          	25,272.943	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" 
sonarlint/ProjectBinder/Start       	25,272.964	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" projectName="Microsoft.CodeAnalysis.InteractiveHost" 
sonarlint/ProjectBinderEnd          	25,322.262	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	25,322.283	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="InteractiveHost32" 
sonarlint/ProjectBinderEnd          	25,369.620	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	25,369.640	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="csi" 
sonarlint/ProjectBinderEnd          	25,417.105	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	25,417.146	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="vbi" 
sonarlint/ProjectBinderEnd          	25,459.920	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	25,459.938	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.VisualStudio.LanguageServices" 
sonarlint/ProjectBinderEnd          	25,564.085	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	25,564.113	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.VisualStudio.LanguageServices.Implementation" 
sonarlint/ProjectBinderEnd          	25,707.429	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	25,707.466	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.VisualStudio.LanguageServices.VisualBasic" 
sonarlint/ProjectBinderEnd          	25,767.741	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	25,767.762	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.VisualStudio.LanguageServices.CSharp" 
sonarlint/ProjectBinderEnd          	25,838.272	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	25,838.296	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Roslyn.VisualStudio.Setup" 
sonarlint/ProjectBinderEnd          	25,894.788	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	25,894.811	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Roslyn.VisualStudio.DiagnosticsWindow" 
sonarlint/ProjectBinderEnd          	25,972.597	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	25,972.632	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="ExpressionEvaluatorPackage" 
sonarlint/ProjectBinderEnd          	26,032.139	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" 
sonarlint/ProjectBinder/Start       	26,032.168	devenv (13612)	ThreadID="22,064" ProcessorNumber="5" projectName="Microsoft.CodeAnalysis.CSharp.ExpressionCompiler" 
sonarlint/ProjectBinderEnd          	26,096.638	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	26,096.684	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.VisualBasic.ExpressionCompiler" 
sonarlint/ProjectBinderEnd          	26,162.621	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	26,162.647	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.ExpressionCompiler" 
sonarlint/ProjectBinderEnd          	26,341.127	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	26,341.155	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="Microsoft.CodeAnalysis.ExpressionCompiler.Utilities" 
sonarlint/ProjectBinderEnd          	26,436.538	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	26,436.566	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.ResultProvider.Utilities" 
sonarlint/ProjectBinderEnd          	26,492.447	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	26,492.470	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="BasicResultProvider.NetFX20" 
sonarlint/ProjectBinderEnd          	26,630.140	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	26,630.161	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.VisualBasic.ResultProvider" 
sonarlint/ProjectBinderEnd          	26,676.515	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	26,676.535	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="CSharpResultProvider.NetFX20" 
sonarlint/ProjectBinderEnd          	26,725.652	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" 
sonarlint/ProjectBinder/Start       	26,725.676	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" projectName="Microsoft.CodeAnalysis.CSharp.ResultProvider" 
sonarlint/ProjectBinderEnd          	26,779.496	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" 
sonarlint/ProjectBinder/Start       	26,779.524	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" projectName="ResultProvider.NetFX20" 
sonarlint/ProjectBinderEnd          	26,837.554	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	26,837.575	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.ResultProvider" 
sonarlint/ProjectBinderEnd          	26,889.643	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	26,889.667	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="vbc" 
sonarlint/ProjectBinderEnd          	27,003.607	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" 
sonarlint/ProjectBinder/Start       	27,003.636	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" projectName="Roslyn.Hosting.Diagnostics" 
sonarlint/ProjectBinderEnd          	27,063.156	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	27,063.178	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Roslyn.Compilers.Extension" 
sonarlint/ProjectBinderEnd          	27,175.356	devenv (13612)	ThreadID="22,064" ProcessorNumber="12" 
sonarlint/ProjectBinder/Start       	27,175.386	devenv (13612)	ThreadID="22,064" ProcessorNumber="12" projectName="Microsoft.VisualStudio.LanguageServices.Xaml" 
sonarlint/ProjectBinderEnd          	27,239.742	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	27,239.765	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.Remote.Workspaces" 
sonarlint/ProjectBinderEnd          	27,297.220	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	27,297.242	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.Remote.ServiceHub" 
sonarlint/ProjectBinderEnd          	27,389.476	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	27,389.530	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.Build.Tasks.CodeAnalysis" 
sonarlint/ProjectBinderEnd          	27,439.398	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	27,439.417	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="BuildBoss" 
sonarlint/ProjectBinderEnd          	27,509.025	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	27,509.063	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.FunctionResolver" 
sonarlint/ProjectBinderEnd          	27,560.860	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	27,560.898	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Roslyn.VisualStudio.Setup.Dependencies" 
sonarlint/ProjectBinderEnd          	27,648.304	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	27,648.331	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.CodeStyle" 
sonarlint/ProjectBinderEnd          	27,729.735	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	27,729.755	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.CodeStyle.Fixes" 
sonarlint/ProjectBinderEnd          	27,818.999	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	27,819.026	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.CSharp.CodeStyle" 
sonarlint/ProjectBinderEnd          	27,884.939	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	27,884.963	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes" 
sonarlint/ProjectBinderEnd          	27,985.554	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" 
sonarlint/ProjectBinder/Start       	27,985.583	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" projectName="Microsoft.CodeAnalysis.VisualBasic.CodeStyle" 
sonarlint/ProjectBinderEnd          	28,043.205	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
sonarlint/ProjectBinder/Start       	28,043.231	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" projectName="Microsoft.CodeAnalysis.VisualBasic.CodeStyle.Fixes" 
sonarlint/ProjectBinderEnd          	28,121.639	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	28,121.672	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.EditorFeatures.Wpf" 
sonarlint/ProjectBinderEnd          	28,201.643	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	28,201.671	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="AnalyzerRunner" 
sonarlint/ProjectBinderEnd          	28,249.630	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" 
sonarlint/ProjectBinder/Start       	28,249.649	devenv (13612)	ThreadID="22,064" ProcessorNumber="0" projectName="Microsoft.CodeAnalysis.Debugging.Package" 
sonarlint/ProjectBinderEnd          	28,300.161	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	28,300.183	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.PooledObjects.Package" 
sonarlint/ProjectBinderEnd          	28,385.036	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" 
sonarlint/ProjectBinder/Start       	28,385.074	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" projectName="InteractiveHost64" 
sonarlint/ProjectBinderEnd          	28,438.314	devenv (13612)	ThreadID="22,064" ProcessorNumber="11" 
sonarlint/ProjectBinder/Start       	28,438.369	devenv (13612)	ThreadID="22,064" ProcessorNumber="11" projectName="Microsoft.Net.Compilers.Package" 
sonarlint/ProjectBinderEnd          	28,515.880	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	28,515.913	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.NETCore.Compilers.Package" 
sonarlint/ProjectBinderEnd          	28,562.734	devenv (13612)	ThreadID="22,064" ProcessorNumber="11" 
sonarlint/ProjectBinder/Start       	28,562.776	devenv (13612)	ThreadID="22,064" ProcessorNumber="11" projectName="Microsoft.CodeAnalysis.Compilers.Package" 
sonarlint/ProjectBinderEnd          	28,637.866	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	28,637.898	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.Scripting.Package" 
sonarlint/ProjectBinderEnd          	28,690.693	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" 
sonarlint/ProjectBinder/Start       	28,690.727	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" projectName="Microsoft.CodeAnalysis.EditorFeatures.Package" 
sonarlint/ProjectBinderEnd          	28,745.621	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" 
sonarlint/ProjectBinder/Start       	28,745.650	devenv (13612)	ThreadID="22,064" ProcessorNumber="7" projectName="VS.ExternalAPIs.Roslyn.Package" 
sonarlint/ProjectBinderEnd          	28,799.725	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" 
sonarlint/ProjectBinder/Start       	28,799.749	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" projectName="VS.Tools.Roslyn.Package" 
sonarlint/ProjectBinderEnd          	28,900.964	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	28,900.993	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.Package" 
sonarlint/ProjectBinderEnd          	28,950.489	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	28,950.540	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.CodeAnalysis.Compilers.Setup" 
sonarlint/ProjectBinderEnd          	29,003.834	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" 
sonarlint/ProjectBinder/Start       	29,003.856	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" projectName="Installer.Package" 
sonarlint/ProjectBinderEnd          	29,054.156	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" 
sonarlint/ProjectBinder/Start       	29,054.178	devenv (13612)	ThreadID="22,064" ProcessorNumber="10" projectName="DevDivInsertionFiles" 
sonarlint/ProjectBinderEnd          	29,100.634	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,100.656	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.ExternalAccess.FSharp" 
sonarlint/ProjectBinderEnd          	29,166.470	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,166.504	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.ExternalAccess.Razor" 
sonarlint/ProjectBinderEnd          	29,217.602	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	29,217.624	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Microsoft.VisualStudio.LanguageServices.CodeLens" 
sonarlint/ProjectBinderEnd          	29,321.542	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,321.582	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.Net.Compilers.Toolset.Package" 
sonarlint/ProjectBinderEnd          	29,373.062	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
sonarlint/ProjectBinder/Start       	29,373.084	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" projectName="Microsoft.CodeAnalysis.LanguageServer.Protocol" 
sonarlint/ProjectBinderEnd          	29,429.441	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,429.475	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.ExternalAccess.Debugger" 
sonarlint/ProjectBinderEnd          	29,482.136	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,482.164	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.ExternalAccess.Xamarin.Remote" 
sonarlint/ProjectBinderEnd          	29,532.413	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" 
sonarlint/ProjectBinder/Start       	29,532.433	devenv (13612)	ThreadID="22,064" ProcessorNumber="3" projectName="Roslyn.VisualStudio.Setup.ServiceHub" 
sonarlint/ProjectBinderEnd          	29,647.713	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" 
sonarlint/ProjectBinder/Start       	29,647.753	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" projectName="Microsoft.CodeAnalysis.ExternalAccess.Apex" 
sonarlint/ProjectBinderEnd          	29,701.511	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	29,701.530	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.VisualStudio.LanguageServices.LiveShare" 
sonarlint/ProjectBinderEnd          	29,759.170	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" 
sonarlint/ProjectBinder/Start       	29,759.192	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" projectName="IdeBenchmarks" 
sonarlint/ProjectBinderEnd          	29,812.224	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	29,812.244	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="CompilersIOperationGenerator" 
sonarlint/ProjectBinderEnd          	29,865.173	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	29,865.195	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator" 
sonarlint/ProjectBinderEnd          	29,922.697	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" 
sonarlint/ProjectBinder/Start       	29,922.726	devenv (13612)	ThreadID="22,064" ProcessorNumber="6" projectName="IdeCoreBenchmarks" 
sonarlint/ProjectBinderEnd          	29,981.869	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	29,981.896	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="BuildValidator" 
sonarlint/ProjectBinderEnd          	30,091.952	devenv (13612)	ThreadID="22,064" ProcessorNumber="9" 
sonarlint/ProjectBinder/Start       	30,091.990	devenv (13612)	ThreadID="22,064" ProcessorNumber="9" projectName="BuildActionTelemetryTable" 
sonarlint/ProjectBinderEnd          	30,143.498	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" 
sonarlint/ProjectBinder/Start       	30,143.520	devenv (13612)	ThreadID="22,064" ProcessorNumber="1" projectName="Microsoft.CodeAnalysis.EditorFeatures.Cocoa" 
sonarlint/ProjectBinderEnd          	30,210.055	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	30,210.085	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.XunitHook" 
sonarlint/ProjectBinderEnd          	30,259.094	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	30,259.117	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="CodeStyleConfigFileGenerator" 
sonarlint/ProjectBinderEnd          	30,308.884	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" 
sonarlint/ProjectBinder/Start       	30,308.913	devenv (13612)	ThreadID="22,064" ProcessorNumber="4" projectName="Microsoft.CodeAnalysis.Collections.Package" 
sonarlint/ProjectBinderEnd          	30,361.477	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" 
sonarlint/ProjectBinder/Start       	30,361.501	devenv (13612)	ThreadID="22,064" ProcessorNumber="13" projectName="Microsoft.CodeAnalysis.Rebuild" 
sonarlint/ProjectBinderEnd          	30,470.628	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" 
sonarlint/ProjectBinder/Start       	30,470.656	devenv (13612)	ThreadID="22,064" ProcessorNumber="2" projectName="Microsoft.CodeAnalysis.ExternalAccess.OmniSharp" 
sonarlint/ProjectBinderEnd          	30,534.514	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" 
sonarlint/ProjectBinder/Start       	30,534.545	devenv (13612)	ThreadID="22,064" ProcessorNumber="8" projectName="Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.CSharp" 
sonarlint/ProjectBinderEnd          	30,667.320	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
sonarlint/ProjectBinder/Start       	30,667.358	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" projectName="Microsoft.CodeAnalysis.Remote.ServiceHub.CoreComponents" 
sonarlint/ProjectBinderEnd          	30,717.081	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
sonarlint/UnboundProjectFinderEnd   	30,717.410	devenv (13612)	ThreadID="22,064" ProcessorNumber="14" 
```

For info, the `Microsoft-VisualStudio/ExtensionUIUnresponsiveness` event contains the following information (the event below was taken from a different trace to the one above):

```
Event Name                                        	 Time MSec	Process Name  	Rest  
Microsoft-VisualStudio/ExtensionUIUnresponsiveness	28,337.190	devenv (25616)	ThreadID="33,224" ProcessorNumber="12" DelayID="1" Duration="8,550.805" Extension="SonarLint.0DE19254-1DCA-4479-8EAF-58E5D677FF4D" 
```

VS version(s): repro-ed with VS2019 and VS2022; no reason to think 2017 is not affected.
SLVS: <= v5.1.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #2791

Overview:

The basic fix is to start on the background thread, and switch to the UI thread when checking an individual project.

The fix breaks into three main parts:

1) `UnboundProjectFinder`: this is where the bottleneck occurs. It now expects to start on the background thread, and takes care of the thread switching. This meant adding methods to our `IThreadHandling` abstraction.

2) Fixing the classes that call `UnboundProjectFinder`, of which there are two.

2a) `ErrorListInfoBarController`: this is the entry point that was causing the gold bar. It too now needs the `IThreadHandling` abstraction. The logic is unchanged, but the previous code is split into synchronous and asynchronous methods as appropriate. Where a synchronous method calls an async method, it either `Forgets` it i.e. doesn't wait for the result, or blocks.

2b) `BindingWorkflow`: this one was simpler. The workflow already declared which thread each step should be run on, so it was just a case of changing the step that calls `UnboundProjectFinder` to run a background thread.
I did try leaving the step to start on the UI thread, and using `IThreadHandling` inside the step to synchronously block while calling the `UnboundProjectFinder` on the background thread. However, the UI deadlocked.

There are multiple commits, but they are all pretty much self-contained and can be reviewed independently.

### CODE REVIEW

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 1]
```diff
@@ -44,9 +45,16 @@ public UnboundProjectFinder(IServiceProvider serviceProvider, ILogger logger)
...
+            if (serviceProvider == null)
+            {
+                throw new ArgumentNullException(nameof(serviceProvider));
+            }
+
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             this.projectBinderFactory = projectBinderFactory ?? throw new ArgumentNullException(nameof(projectBinderFactory));
+
+            configProvider = serviceProvider.GetService<IConfigurationProviderService>();
+            projectSystem = serviceProvider.GetService<IProjectSystemHelper>();
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:63]: Moved the `GetService` calls to the constructor - reduces the number of thread-switches that are required in the rest of the code.

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs [hunk 2]
```diff
@@ -65,17 +68,17 @@ public void GetUnboundProjects_ValidSolution_ReturnsProjectsThatRequireBinding(i
 
             foreach (var boundProject in boundProjects)
             {
-                testConfig.SetupProjectBindingRequired(boundProject, true);
+                testConfig.SetupProjectBindingRequired(boundProject, false);
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:71]: Fixing bugs in the existing test. The setup was mixing up bound and unbound projects during initialization, and the assertion wasn't detecting incorrect results.

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs [hunk 3]
```diff
@@ -96,7 +99,7 @@ private class TestConfigurationBuilder
         {
             private readonly Mock<IProjectBinderFactory> projectBinderFactoryMock = new Mock<IProjectBinderFactory>();
             private readonly List<ProjectMock> projects = new List<ProjectMock>();
-            private readonly BindingConfiguration bindingConfiguration = BindingConfiguration.Standalone;
+            private readonly BindingConfiguration bindingConfiguration = new BindingConfiguration(new BoundSonarQubeProject(), SonarLintMode.Connected, null);
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:102]: Another problem with the existing test setup: it was using standalone mode, so most of the "find unbound" logic was being skipped.

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs [hunk 4]
```diff
@@ -130,9 +133,21 @@ public UnboundProjectFinder CreateTestSubject()
                 sp.RegisterService(typeof(IProjectSystemHelper), projectSystemHelper.Object);
                 sp.RegisterService(typeof(IConfigurationProviderService), configProviderMock.Object);
 
-                var testSubject = new UnboundProjectFinder(sp, new TestLogger(), projectBinderFactoryMock.Object);
+                var testSubject = new UnboundProjectFinder(sp, new TestLogger(), projectBinderFactoryMock.Object, CreateThreadHandlingWithRunPassthrough().Object);
                 return testSubject;
             }
+
+            private static Mock<IThreadHandling> CreateThreadHandlingWithRunPassthrough()
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:140]: FYI I added some more methods to the interface in a later commit, at which point I create a helper class in the `TestInfrastructure` project (simpler than mocking).

I can't remember if I removed this use of a mocked version, though.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 5]
```diff
@@ -37,13 +40,15 @@ internal class UnboundProjectFinder : IUnboundProjectFinder
         private readonly IConfigurationProviderService configProvider;
         private readonly IProjectSystemHelper projectSystem;
         private readonly ILogger logger;
+        private readonly IThreadHandling threadHandling;
 
         public UnboundProjectFinder(IServiceProvider serviceProvider, ILogger logger)
-            : this(serviceProvider, logger, new ProjectBinderFactory(serviceProvider, logger))
+            : this(serviceProvider, logger, new ProjectBinderFactory(serviceProvider, logger), new ThreadHandling())
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:46]: Basically, the fix is to change this class so the checking is not all done on the UI thread.

* the processing is expected to start on a background thread.
* the class switches to the UI thread each time it checks a project
i.e. there are a lot of switches back and forth. However, we`re not monopolising the UI thread, so the gold bar doesn't appear.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 6]
```diff
@@ -76,31 +84,80 @@ public IEnumerable<Project> GetUnboundProjects()
...
-            logger.LogDebug($"[Binding check] Number of bindable projects: {filteredSolutionProjects.Length}");
+            // Using threadHandling.Run(...) here to avoid having to convert all of the upstream
+            // // calling methods to be async.
+            var projects = threadHandling.Run(() => GetUnboundProjectsAsync(binding));
+
+            threadHandling.ThrowIfOnUIThread();
+            return projects;
+        }
 
-            var result = filteredSolutionProjects
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:83]: The logic is the same as in the previous `Where` clause. However, each inner iteration involves a thread switch to the UI thread.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 7]
```diff
@@ -76,31 +84,80 @@ public IEnumerable<Project> GetUnboundProjects()
...
+                    unboundProjects.Add(project);
+                }
+            }
+
+            return unboundProjects.ToArray();
+        }
+
+        private async Task<Project[]> GetFilteredSolutionProjectsAsync()
+        {
+            threadHandling.ThrowIfOnUIThread();
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:126]: Expecting to start on a background thread, but switches to the UI thread to do the work, blocking the background thread until it is done.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 8]
```diff
@@ -76,31 +84,80 @@ public IEnumerable<Project> GetUnboundProjects()
...
+                logger.LogDebug($"[Binding check] Number of bindable projects: {filteredSolutionProjects.Length}");
+            });
+
+            return filteredSolutionProjects;
+        }
+
+        private async Task<bool> IsBindingRequiredAsync(Project project, BindingConfiguration binding)
+        {
+            bool isBindingRequired = false;
+            await threadHandling.RunOnUIThread(() => isBindingRequired = IsBindingRequired(project, binding));
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:141]: Again, blocks the background thread while the check is done on the UI thread.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 9]
```diff
@@ -76,31 +84,80 @@ public IEnumerable<Project> GetUnboundProjects()
...
+            return isBindingRequired;
+        }
+
+        private bool IsBindingRequired(Project project, BindingConfiguration binding)
+        {
+            threadHandling.ThrowIfNotOnUIThread();
 
-                    var projectName = project.Name;
-                    ETW.CodeMarkers.Instance.CheckProjectBindingStart(projectName);
+            var configProjectBinder = projectBinderFactory.Get(project);
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:149]: This sync method is run on the UI thread, and contains what was in the body of the `Where` clause.

File: src/Infrastructure.VS/ThreadHandling.cs [hunk 10]
```diff
@@ -39,5 +41,7 @@ public class ThreadHandling : IThreadHandling
         public async Task RunOnUIThread(Action op) => await VS.RunOnUIThread.RunAsync(op);
 
         public T Run<T>(Func<System.Threading.Tasks.Task<T>> asyncMethod) => ThreadHelper.JoinableTaskFactory.Run(asyncMethod);
+
+        public async Task SwitchToBackgroundThread() => await TaskScheduler.Default;
```
Comment (duncanp-sonar) [inline src/Infrastructure.VS/ThreadHandling.cs]: This version doesn't work. It's replaced in a later commit.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 11]
```diff
@@ -56,7 +58,7 @@ public class ErrorListInfoBarControllerTests
         private ConfigurableConfigurationProvider configProvider;
         private ConfigurableStateManager stateManager;
         private Mock<IKnownUIContexts> knownUIContexts;
-        private ILogger logger;
+        private TestLogger logger;
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:61]: Miscellaneous: minor test cleanup. Some of the tests were creating their own `TestLogger` instances if they needed to check logged output. This one already existed, so there was no need.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 12]
```diff
@@ -182,7 +184,7 @@ public void ErrorListInfoBarController_Refresh_Connected_ActiveSolutionBoundAndF
         }
 
         [TestMethod]
-        public void ErrorListInfoBarController_Refresh_ActiveSolutionBound_NotFullyLoaded_HasUnboundProjects()
+        public async Task ErrorListInfoBarController_Refresh_ActiveSolutionBound_NotFullyLoaded_HasUnboundProjects()
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:187]: The product code now contains an `async` class so some of the tests need to be changed to be `async` too.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 13]
```diff
@@ -197,14 +199,14 @@ public void ErrorListInfoBarController_Refresh_ActiveSolutionBound_NotFullyLoade
 
             // Assert
             // Action should have been queued because the context is not active
-            uiContext.Verify(x => x.WhenActivated(testSubject.ProcessSolutionBinding), Times.Once());
+            uiContext.Verify(x => x.WhenActivated(It.IsAny<Action>()), Times.Once());
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:202]: The synchronous product method is now private. This was the only place that used it, so I decided to make the assertion weaker rather than making the product method more visible.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 14]
```diff
@@ -272,15 +274,15 @@ public void ErrorListInfoBarController_CurrentBackgroundProcessorCancellation()
...
 
             // Assert
             testSubject.CurrentBackgroundProcessor?.BackgroundTask.Should().NotBeNull("Background task is expected");
             testSubject.CurrentBackgroundProcessor.BackgroundTask.Wait(TimeSpan.FromSeconds(2)).Should().BeTrue("Timeout waiting for the background task");
             this.infoBarManager.AssertHasNoAttachedInfoBar(ErrorListInfoBarController.ErrorListToolWindowGuid);
 
-            // Act (refresh again and  let the blocked UI thread run to completion)
-            testSubject.ProcessSolutionBinding();
+            // Act (refresh again and let the blocked UI thread run to completion)
+            await testSubject.ProcessSolutionBindingAsync();
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:285]: There is still a synchronous `ProcessSolutionBinding` method. However, it calls `ProcessSolutionBindingAsync().Forget`, which returns immediately. So the tests now need to call the async method and wait for it to finish.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 15]
```diff
@@ -289,26 +291,25 @@ public void ErrorListInfoBarController_CurrentBackgroundProcessorCancellation()
         }
 
         [TestMethod]
-        public void ErrorListInfoBarController_Refresh_NonCriticalExceptionIsSuppressed()
+        public async Task ErrorListInfoBarController_Refresh_NonCriticalExceptionIsSuppressed()
         {
-            var logger = new TestLogger();
             var host = CreateHostWithThrowingConfigProvider(new COMException("thrown by test code"));
-            var testSubject = new ErrorListInfoBarController(host, Mock.Of<IUnboundProjectFinder>(), logger);
+            var testSubject = CreateTestSubject(host);
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:297]: Miscellaneous: most of the test were using the `CreateTestSubject` method but not all. Now they all do.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 16]
```diff
@@ -1026,6 +1030,18 @@ private static void VerifyInfoBar(ConfigurableInfoBar infoBar)
             infoBar.Image.Should().BeEquivalentTo(new SonarLintImageMoniker(KnownMonikers.RuleWarning.Guid, KnownMonikers.RuleWarning.Id));
         }
 
+        private static Mock<IThreadHandling> CreateThreadHandlingWithRunPassthrough()
+        {
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs]: This is replaced with a helper class in a subsequent commit.

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 17]
```diff
@@ -76,15 +80,17 @@ public ErrorListInfoBarController(IHost host, IUnboundProjectFinder unboundProje
...
         {
-            this.AssertOnUIThread();
+            threadHandling.ThrowIfNotOnUIThread();
 
             this.ClearCurrentInfoBar();
         }
 
         public void Refresh()
         {
+            logger.LogDebug("[ErrorListInfoBarController] In Refresh");
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs:90]: I added a few debug statements to make it easier to see what was happening in the UI.

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 18]
```diff
@@ -112,17 +119,6 @@ public void Refresh()
             private set;
         }
 
-        [Conditional("DEBUG")]
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs:115]: No longer necessary. I changed the code from asserting to throwing if it is called on the wrong thread. There are only a couple of callers, so we'll soon find out if I missed one :-)

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 19]
```diff
@@ -141,6 +137,11 @@ private void InvokeWhenIdle(Action action)
         }
 
         private void ClearCurrentInfoBar()
+        {
+            ClearCurrentInfoBarAsync().Forget();
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs:141]: Clearing the info bar is still called from some synchronous code paths e.g. when the user clicks on a button. Those scenarios can safely be turned into "fire and forget".

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 20]
```diff
@@ -170,13 +175,22 @@ private void CancelQualityProfileProcessing()
...
-        internal /*for testing purposes*/ void ProcessSolutionBinding()
+        private void ProcessSolutionBinding()
+        {
+            logger.LogDebug("[ErrorListInfoBarController] Processing solution binding...");
+            ProcessSolutionBindingAsync().Forget();
+        }
+
+        internal/* for testing */ async Task ProcessSolutionBindingAsync()
         {
+            logger.LogDebug("[ErrorListInfoBarController] Processing solution binding...");
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs:186]: I hadn`t noticed I was logging the same debug message twice (here and in line 180).
I'll remove one.

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 21]
```diff
@@ -170,13 +175,22 @@ private void CancelQualityProfileProcessing()
...
+
             ETW.CodeMarkers.Instance.ErrorListControllerProcessStart();
 
-            // We could be on a UI thread so any unhandled exceptions will crash VS.
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs:177]: This comment is no longer accurate - we're shouldn't be on the UI thread. However, we're still handling exceptions.

File: src/Integration/LocalServices/ErrorListInfoBarController.cs [hunk 22]
```diff
@@ -170,13 +175,22 @@ private void CancelQualityProfileProcessing()
...
-            // We can't catch at a higher level as this method queues a recursive callback
-            // if the solution is not fully loaded.
+            await threadHandling.SwitchToBackgroundThread();
+
+            threadHandling.ThrowIfOnUIThread();
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/ErrorListInfoBarController.cs]: Sanity check that switching to the background thread actually worked.

File: src/Core/IThreadHandling.cs [hunk 23]
```diff
@@ -62,6 +63,24 @@ public interface IThreadHandling
         /// Switches to the background thread
         /// </summary>
         /// <remarks>Wrapper that calls <see cref="TaskScheduler.Default"/></remarks>
-        Task SwitchToBackgroundThread();
+        IAwaitableWrapper SwitchToBackgroundThread();
```
Comment (duncanp-sonar) [inline src/Core/IThreadHandling.cs:66]: The previous version didn't work - we need to return an awaiter, not a task.

However, we don't want to expose VS directly types in `Core`, so we wrap them.

File: src/Core/IThreadHandling.cs [hunk 24]
```diff
@@ -62,6 +63,24 @@ public interface IThreadHandling
...
+
+    // Wrappers for awaiter /awaitable to avoid VS-specific types on the interface
+    public interface IAwaitableWrapper
+    {
+        IAwaiterWrapper GetAwaiter();
+    }
+
+    public interface IAwaiterWrapper :
+#if VS2022
+        // Earlier versions of VS don't implement ICriticalNotifyCompletion
```
Comment (duncanp-sonar) [inline src/Core/IThreadHandling.cs:77]: I didn't realise this until the PR build failed for VS2017 and VS2019.
I looked at the VS2019 version in DotPeek to check that it only implements the non-critical version.

File: src/Infrastructure.VS/Infrastructure.VS.csproj [hunk 25]
```diff
@@ -3,6 +3,13 @@
   <Import Project="..\SonarLint.Product.props" />
   <Import Project="..\SonarLint.VsPkgRefs.props" />
 
+  <PropertyGroup>
+    <!-- Conditional compilation constant for VS2019-specific code.
+         We'd prefer to set this the shared SonarLint.VSSpecificAssemblies.props file, but
+         the IDE isn't picking up the setting if we do that. -->
+    <DefineConstants Condition="($(VisualStudioVersion)=='17.0' AND $(BuildingInsideVisualStudio)=='true') OR $(VSTargetVersion)=='2022'">$(DefineConstants);VS2022</DefineConstants>
+  </PropertyGroup>
```
Comment (duncanp-sonar) [inline src/Infrastructure.VS/Infrastructure.VS.csproj:11]: Copied from the `TeamExplorer` project and tweaked for VS2022.

File: src/Infrastructure.VS/ThreadHandling.cs [hunk 26]
```diff
@@ -40,8 +41,51 @@ public class ThreadHandling : IThreadHandling
 
         public async Task RunOnUIThread(Action op) => await VS.RunOnUIThread.RunAsync(op);
 
-        public T Run<T>(Func<System.Threading.Tasks.Task<T>> asyncMethod) => ThreadHelper.JoinableTaskFactory.Run(asyncMethod);
+        public T Run<T>(Func<Task<T>> asyncMethod) => ThreadHelper.JoinableTaskFactory.Run(asyncMethod);
+
+        public IAwaitableWrapper SwitchToBackgroundThread() => new TaskSchedulerAwaitableWrapper(new AwaitExtensions.TaskSchedulerAwaitable(TaskScheduler.Default));
+
+        #region Wrappers for VS TaskSchedule awaiter/awaitable structs
```
Comment (duncanp-sonar) [inline src/Infrastructure.VS/ThreadHandling.cs:47]: The normal approach to making a type `awaitable` is to have two structs:
- one that acts as a factory. It implements `GetAwaiter` to return the second struct.
- a struct that has the three required methods: `OnCompleted`, `IsCompleted`, `GetResult`.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs [hunk 27]
```diff
@@ -309,7 +309,7 @@ public async Task ErrorListInfoBarController_Refresh_CriticalExceptionIsNotSuppr
             var testSubject = CreateTestSubject(host);
 
             // Act
-            var act = async () => await testSubject.ProcessSolutionBindingAsync();
+            Func<Task> act = async () => await testSubject.ProcessSolutionBindingAsync();
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:312]: Fixing a test compilation error from a previous commit.

The test projects are set to use the `latest` C# language version. Building with VS2022/MSBuild v17.0 means we can use `var` here i.e. on our dev machines.

However, the CI machine is still using MSBuild v16.0, so we can't use `var` here.

File: src/TestInfrastructure/NoOpThreadHandler.cs [hunk 28]
```diff
@@ -0,0 +1,65 @@
...
+ * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+ */
+
+using System;
+using System.Threading.Tasks;
+using SonarLint.VisualStudio.Core;
+
+namespace SonarLint.VisualStudio.Integration.UnitTests
+{
+    internal class NoOpThreadHandler : IThreadHandling
```
Comment (duncanp-sonar) [inline src/TestInfrastructure/NoOpThreadHandler.cs:27]: All operations are performed synchronously.

File: src/TestInfrastructure/NoOpThreadHandler.cs [hunk 29]
```diff
@@ -0,0 +1,65 @@
...
+    {
+        public bool CheckAccess() => true;
```
Comment (duncanp-sonar) [inline src/TestInfrastructure/NoOpThreadHandler.cs:29]: One weakness of this simplistic implementation is that `CheckAccess()` is hard-coded, which won`t work if the product code asserts `!CheckAccess()`. However, we don't currently do that.

File: src/Integration.UnitTests/Binding/BindingWorkflowTests.cs [hunk 30]
```diff
@@ -119,16 +117,16 @@ public void BindingWorkflow_InstallPackages_NoError()
         }
 
         [TestMethod]
-        public void BindingWorkflow_InitializeSolutionBindingOnUIThread_NoError()
+        public void BindingWorkflow_InitializeSolutionBindingOnBackgroundThread_NoError()
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/Binding/BindingWorkflowTests.cs:120]: Just renaming the tests/method from saying `UIThread` to `BackgroundThread`.

File: src/Integration/Binding/BindingWorkflow.cs [hunk 31]
```diff
@@ -125,8 +126,8 @@ private ProgressStepDefinition[] CreateWorkflowSteps(IProgressController control
                 // * create/update per-project ruleset
                 // * set project-level properties
                 // Most of the work is delegated to SolutionBindingOperation
-                new ProgressStepDefinition(Strings.BindingProjectsDisplayMessage, IndeterminateNonCancellableUIStep,
-                        (token, notifications) => this.InitializeSolutionBindingOnUIThread(notifications)),
+                new ProgressStepDefinition(Strings.BindingProjectsDisplayMessage, IndeterminateNonCancellableBackgroundStep,
```
Comment (duncanp-sonar) [inline src/Integration/Binding/BindingWorkflow.cs:129]: The only necessary change to fix the binding code is to change this step to start on the background thread rather than the UI thread.

The `UnboundProjectFinder` then handles switching on and off the UI thread when necessary.

File: src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs [hunk 32]
```diff
@@ -22,20 +22,13 @@
...
 {
     [TestClass]
     public class ThreadHandlingTests
     {
-        [TestMethod]
-        public void MefCtor_CheckIsExported()
-        {
-            MefTestHelpers.CheckTypeCanBeImported<ThreadHandling, IThreadHandling>(null, null);
-        }
-
```
Comment (duncanp-sonar) [inline src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs:38]: Cleanup. We don't actually want or need to MEF import this type.

**Comment by duncanp-sonar** [comment]
Overview:

The basic fix is to start on the background thread, and switch to the UI thread when checking an individual project.

The fix breaks into three main parts:

1) `UnboundProjectFinder`: this is where the bottleneck occurs. It now expects to start on the background thread, and takes care of the thread switching. This meant adding methods to our `IThreadHandling` abstraction.

2) Fixing the classes that call `UnboundProjectFinder`, of which there are two.

2a) `ErrorListInfoBarController`: this is the entry point that was causing the gold bar. It too now needs the `IThreadHandling` abstraction. The logic is unchanged, but the previous code is split into synchronous and asynchronous methods as appropriate. Where a synchronous method calls an async method, it either `Forgets` it i.e. doesn't wait for the result, or blocks.

2b) `BindingWorkflow`: this one was simpler. The workflow already declared which thread each step should be run on, so it was just a case of changing the step that calls `UnboundProjectFinder` to run a background thread.
I did try leaving the step to start on the UI thread, and using `IThreadHandling` inside the step to synchronously block while calling the `UnboundProjectFinder` on the background thread. However, the UI deadlocked.

There are multiple commits, but they are all pretty much self-contained and can be reviewed independently.

File: src/Infrastructure.VS/ThreadHandling.cs [hunk 33]
```diff
@@ -19,15 +19,17 @@
...
+using Microsoft.VisualStudio.Threading;
 using SonarLint.VisualStudio.Core;
+using static Microsoft.VisualStudio.Threading.AwaitExtensions;
 using Task = System.Threading.Tasks.Task;
 
 namespace SonarLint.VisualStudio.Infrastructure.VS
 {
-    [Export(typeof(IThreadHandling))]
-    [PartCreationPolicy(CreationPolicy.Shared)]
+    [ExcludeFromCodeCoverage] // Simple wrapper around hard-to-test VS types
```
Comment (rita-sonarsource) [inline src/Infrastructure.VS/ThreadHandling.cs:32]: What happened to the MEF attributes?
The class was MEF-imported by CFamily analysis (i.e. VcxRequestFactory)

File: src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs (hunk 32 above)
Comment (rita-sonarsource) [reply src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs:38]: We do, in CFamily code, i.e. VcxRequestFactory -- this is part of the fix I've implemented earlier.

File: src/Integration/Binding/BindingProcessImpl.cs [hunk 34]
```diff
@@ -65,6 +69,7 @@ internal class BindingProcessImpl : IBindingProcess
             this.bindingConfigProvider = bindingConfigProvider ?? throw new ArgumentNullException(nameof(bindingConfigProvider));
             this.bindingMode = bindingMode;
             projectToLanguageMapper = host.GetMefService<IProjectToLanguageMapper>();
+            this.threadHandling = threadHandling ?? new ThreadHandling();
```
Comment (rita-sonarsource) [inline src/Integration/Binding/BindingProcessImpl.cs:72]: If the class goes back to being MEF-importable, this will be a bit unclean, but I looked at the chain and it's ugly all the way up anyway (BindingController.CreateBindingProcess takes some from the host and some are new-ed up) so I guess we can just leave it like that.

File: src/Integration/LocalServices/ErrorListInfoBarController.cs (hunk 18 above)
Comment (rita-sonarsource) [reply src/Integration/LocalServices/ErrorListInfoBarController.cs:115]: How to introduce fun in the workspace!

File: src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs (hunk 32 above)
Comment (duncanp-sonar) [reply src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs:38]: Ah, I missed that when I search for usages. I'll change the `VcxRequestFactory`.

File: src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs (hunk 27 above)
Comment (rita-sonarsource) [reply src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs:312]: Ah, so that's why it failed. Good to know.

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs (hunk 2 above)
Comment (rita-sonarsource) [reply src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:71]: Great tests...

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs [hunk 35]
```diff
@@ -65,17 +68,17 @@ public void GetUnboundProjects_ValidSolution_ReturnsProjectsThatRequireBinding(i
...
             foreach (var boundProject in unboundProjects)
             {
-                testConfig.SetupProjectBindingRequired(boundProject, false);
+                testConfig.SetupProjectBindingRequired(boundProject, true);
             }
 
             var testSubject = testConfig.CreateTestSubject();
 
             var result = testSubject.GetUnboundProjects();
-            result.Should().AllBeEquivalentTo(unboundProjects);
```
Comment (rita-sonarsource) [inline src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:78]: I'm really surprised the tests didn't fail on this sooner: AllBeEquivalentTo is supposed to receive a single object, not a collection.

File: src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs (hunk 4 above)
Comment (rita-sonarsource) [reply src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs:140]: I'm looking at the latest commit and it's still here, so I think it can be replaced.

File: src/Integration/LocalServices/UnboundProjectFinder.cs [hunk 36]
```diff
@@ -71,34 +84,81 @@ public IEnumerable<Project> GetUnboundProjects()
...
         private Project[] GetUnboundProjects(BindingConfiguration binding)
         {
+            threadHandling.ThrowIfOnUIThread();
+
+            Debug.Assert(binding.Mode.IsInAConnectedMode());
+            Debug.Assert(binding.Project != null);
+
+            // Using threadHandling.Run(...) here to avoid having to convert all of the upstream
+            // calling methods to be async.
+            var projects = threadHandling.Run(() => GetUnboundProjectsAsync(binding));
```
Comment (rita-sonarsource) [inline src/Integration/LocalServices/UnboundProjectFinder.cs:94]: Side note: perhaps for readability we should rename `Run` to something more explicit, i.e. `RunOnCurrentThread`, to go along with `RunOnUIThread`

**Review by rita-sonarsource — APPROVED** [review]
Looks good, just the comment about MEF ctor.
