### PR TITLE
Recalculate location span when buffer changes

### LINKED ISSUE #1719: Exception is thrown when closing and re-opening a file with secondary location
Repro:
1. Analyze a file with a secondary location in another file, e.g.

`a.h`:
```
struct TrivCopyPaddingInside { // secondary will be in the file where this class is defined
	int x;
	char color;
	int y;
};
```
`a.cpp`:
```
#include "a.h"
int f() {
	TrivCopyPaddingInside trivCopyPaddingInside;
	auto r = memcmp(&trivCopyPaddingInside, &trivCopyPaddingInside, sizeof trivCopyPaddingInside);
```

2. Open the file with secondary location.
3. Close and re-open the file.

Expected ==> No exception.
Actual ==> AggregateException

### PR DESCRIPTION
**Pull request by rita-g-sonarsource**
Fixes #1719

### CODE REVIEW

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs [hunk 1]
```diff
@@ -73,25 +74,41 @@ private void OnIssuesChanged(object sender, IssuesChangedEventArgs e)
         private void UpdateTags()
         {
             var textSnapshot = buffer.CurrentSnapshot;
+            var oldTags = TagSpans;
+            TagSpans = CreateTagSpans(textSnapshot);
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/LocationTagging/LocationTagger.cs:78]: Extracted previous logic to function

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs [hunk 2]
```diff
@@ -73,25 +74,41 @@ private void OnIssuesChanged(object sender, IssuesChangedEventArgs e)
...
-            EnsureSpansExist(locations, textSnapshot);
 
-            var oldTags = TagSpans;
-            TagSpans = locations.Select(CreateTagSpan).ToList();
+            EnsureUpdatedSpansExist(locations, textSnapshot);
 
-            var affectedSpan = CalculateSpanOfAllTags(oldTags, textSnapshot);
-            NotifyTagsChanged(affectedSpan);
+            var tagSpans = locations
+                .Where(x => x.Span.HasValue && !x.Span.Value.IsEmpty)
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/LocationTagging/LocationTagger.cs:92]: Repro scenario:
1. Open file with secondary location
2. Edit, save and close the file.
3. Open the file ==> new span will be empty and an exception will be thrown in GetTags TranslateTo

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs [hunk 3]
```diff
@@ -73,25 +74,41 @@ private void OnIssuesChanged(object sender, IssuesChangedEventArgs e)
...
+        /// Also, if a file has been closed and re-opened, a new text buffer would've been created. So we need to recalculate the spans since the locations would have spans that belong to the old text buffer.
+        /// </remarks>
+        private void EnsureUpdatedSpansExist(IEnumerable<IAnalysisIssueLocationVisualization> locVizs, ITextSnapshot currentSnapshot)
         {
-            // All spans for issues in the this file should have been calculated when the file was analysed (whether primary or secondary).
-            // However, there could be secondary locations relating to issues in other files that have not been calculated.
             foreach (var locViz in locVizs)
             {
-                if (!locViz.Span.HasValue)
+                if (!locViz.Span.HasValue || locViz.Span.Value.IsEmpty || locViz.Span.Value.Snapshot.TextBuffer != currentSnapshot.TextBuffer)
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/LocationTagging/LocationTagger.cs:111]: First repro scenario:
1. Close and reopen a file with secondary location ==> TextBuffer is different.

Second repro scenario:
1. Open a file with secondary location
2. Delete the code ==> span is empty
3. Close the file without saving & reopen ==> span is falsely empty

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs [hunk 4]
```diff
@@ -131,18 +148,25 @@ private void TranslateTagSpans(ITextSnapshot newSnapshot)
...
+                        old.Tag.Location.InvalidateSpan();
+                    }
+                    else
+                    {
+                        old.Tag.Location.Span = newSpan;
+                        translatedTagSpans.Add(new TagSpan<IIssueLocationTag>(newSpan, old.Tag));
+                    }
                 }
-                else
+                catch (Exception e)
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/LocationTagging/LocationTagger.cs:167]: Wrapping with a try-catch just so we won't crash next time, in case there are other corner cases

Comment (duncanp-sonar) [reply src/IssueViz/Editor/LocationTagging/LocationTagger.cs:167]: Don't suppress critical exceptions

**Review by duncanp-sonar — APPROVED** [review]
