### PR TITLE
CSS analysis fails with System.InvalidOperationException 

### LINKED ISSUE #4119: CSS analysis fails with System.InvalidOperationException
When a css analysis is run it would fail with the below error. 

`System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeIssueConverter.Convert(String filePath, Issue issue)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeAnalyzer.<>c__DisplayClass21_0.<ConvertIssues>b__0(Issue x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeAnalyzer.ConvertIssues(String filePath, IEnumerable`1 analysisResponseIssues)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeAnalyzer.<Analyze>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SonarLint.VisualStudio.TypeScript.Analyzer.AnalyzerBase.<ExecuteAsync>d__10.MoveNext()`

### PR DESCRIPTION
**Pull request by ugras-ergun-sonarsource**
fixes #4119

### CODE REVIEW

File: src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs [hunk 1]
```diff
@@ -160,14 +159,7 @@ public void Convert_KeyMatchingIsCaseInsensitive(string keyInIssue, string keyIn
         {
             var eslintBridgeIssue = new Issue { RuleId = keyInIssue };
 
-            var ruleDefinitions = new[]
```
Comment (ugras-ergun-sonarsource) [inline src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs:163]: CAYC

Comment (georgii-borovinskikh-sonarsource) [reply src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs:163]: 🍰

**Review by georgii-borovinskikh-sonarsource — APPROVED** [review]
