### PR TITLE
Fix the Threading Issue in GitEventsMonitor

### LINKED ISSUE #5020: Fix the Threading Issue in GitEventsMonitor
### Description 

When disposing of GitEventsMonitor and a head change triggered at the same time It would cause a race condition on underlying FileSystemWatcher and causes VS to freeze. 

### Reproduction

If you have a solution which checking out a earlier version triggers reloading of the solution also (this happens if the solution file changed between versions) will cause Visual Studio to freeze and killing the "devenv.exe" would be the only way to move forward.

### PR DESCRIPTION
**Pull request by ugras-ergun-sonarsource**
Fixes #5020

### CODE REVIEW

File: src/Core.UnitTests/GitEventsMonitorTests.cs [hunk 1]
```diff
@@ -46,6 +47,8 @@ public void HeadChanged_EventInvoked()
 
             fileSystemWatcher.Raise(w => w.Renamed += null, null, null);
 
+            Task.Delay(10).Wait();
```
Comment (ugras-ergun-sonarsource) [inline src/Core.UnitTests/GitEventsMonitorTests.cs:50]: A short wait is needed since we are now firing and forgetting.

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM
Please try those two other ways of solving the wait in UTs. I can't test it myself.

File: src/Core.UnitTests/GitEventsMonitorTests.cs (hunk 1 above)
Comment (ugras-ergun-sonarsource) [reply src/Core.UnitTests/GitEventsMonitorTests.cs]: yes they work I pushed the changes
