### PR TITLE
Fix tooltip bug

### LINKED ISSUE #1720: Tooltips do not appear for primary locations
Repro steps:

1. Analyze a file that creates an issue.
2. Hover over the squiggly in the editor

Expected ==> Tooltip is shown.
Actual ==> No tooltip.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #1720

### CODE REVIEW

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs [hunk 1]
```diff
@@ -172,8 +172,13 @@ private void TranslateTagSpans(ITextSnapshot newSnapshot)
...
         }
 
-        private static bool OverlapsExists(Span span, NormalizedSnapshotSpanCollection spans) =>
-            spans.Any(x => x.OverlapsWith(span));
+        private static bool IntersectionExists(Span span, NormalizedSnapshotSpanCollection spans) =>
+            // We're using "IntersectsWith" rather than "OverlapsWith" so that zero-length spans are handled correctly.
+            // Given two spans A = [10 -> 15] and B = [12 -> 12],
+            // * A.IntersectsWith(B) == true
+            // * A.OverlapsWith(B) == false.
+            // This matters because when VS is requesting tags to show tooltips it uses a zero-length span.
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/LocationTagging/LocationTagger.cs:180]: It uses a zero-length span?? Ohhh so that's why!

**Review by rita-g-sonarsource — APPROVED** [review]

File: src/IssueViz/Editor/LocationTagging/LocationTagger.cs (hunk 1 above)
Comment (duncanp-sonar) [reply src/IssueViz/Editor/LocationTagging/LocationTagger.cs:180]: Yep, and an empty span overlaps with nothing, even itself.  However, it will intersect.

Comment (rita-g-sonarsource) [reply src/IssueViz/Editor/LocationTagging/LocationTagger.cs:180]: 🤦 🤯
