### PR TITLE
SLCoreServiceProvider.TryGetTransientService should catch exceptions from jsonRpc.CreateService

### LINKED ISSUE #5194: SLCoreServiceProvider.TryGetTransientService should catch exceptions from jsonRpc.CreateService

### PR DESCRIPTION
**Pull request by ugras-ergun-sonarsource**
Fixes #5194

### CODE REVIEW

File: src/SLCore.UnitTests/Core/SLCoreServiceProviderTests.cs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 ﻿/*
  * SonarLint for Visual Studio
- * Copyright (C) 2016-2023 SonarSource SA
+ * Copyright (C) 2016-2024 SonarSource SA
```
Comment (georgii-borovinskikh-sonarsource) [inline src/SLCore.UnitTests/Core/SLCoreServiceProviderTests.cs:3]: This should have been done during the rebase

File: src/SLCore.UnitTests/Core/SLCoreServiceProviderTests.cs [hunk 2]
```diff
@@ -74,6 +77,23 @@ public void TryGetTransientService_ConnectionDied_ReturnsFalse()
         testSubject.TryGetTransientService(out ITestSLcoreService1 _).Should().BeFalse();
     }
 
+    [TestMethod]
+    public void TryGetTransientService_Rpcthrows_LoggedAndReturnsFalse()
```
Comment (georgii-borovinskikh-sonarsource) [inline src/SLCore.UnitTests/Core/SLCoreServiceProviderTests.cs:81]: Throws
