### PR TITLE
Do not allow to install new major version SonarC# / SonarVB on old VS

### LINKED ISSUE #500: Do not allow to install new major version SonarC# / SonarVB on old VS
### Description

Next major version release of SonarC# and SonarVB will rely on Roslyn 1.3 which implies to have Visual Studio 2015 Update 3+. In order to avoid broken behaviors we need to make sure that if the user is in a Visual Studio < Update 3 it won't allow installation of the NuGet (in connected mode) if the new versions of SonarC#/VB are installed on the bound SonarQube/SonarCloud.

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #500

### CODE REVIEW

File: src/Integration/Helpers/VisualStudioHelpers.cs [hunk 1]
```diff
@@ -26,7 +26,20 @@ namespace SonarLint.VisualStudio.Integration
 {
     public static class VisualStudioHelpers
     {
-        public static readonly string VisualStudioVersion = GetVisualStudioVersion();
+        private static readonly Version visualStudio2015Update3Version = Version.Parse("14.0.25420.00");
+
+        public static string VisualStudioVersion
+        {
+            get;
+            /* for testing purpose only */ internal set;
```
Comment (Evangelink) [inline src/Integration/Helpers/VisualStudioHelpers.cs]: Ideally I should have created a service instead of this static class and then asked for the service in the right locations but I was lazy.

File: src/Integration/Connection/ConnectionWorkflow.cs [hunk 2]
```diff
@@ -319,10 +319,43 @@ private string GetPluginProjectMismatchErrorMessage(ICollection<EnvDTE.Project>
...
+
+            // Let's handle specific case for old Visual Studio instances
+            if (isPluginSupported &&
+                VisualStudioHelpers.IsVisualStudioBeforeUpdate3())
+            {
+                if (minimumSupportedPlugin == MinimumSupportedSonarQubePlugin.CSharp)
+                {
+                    const string newRoslynSonarCSharpVersion = "7.0";
+                    pluginInfoMessage += $", Maximum version: '{newRoslynSonarCSharpVersion}'";
+                    isPluginSupported = VersionHelper.Compare(plugin.Version, newRoslynSonarCSharpVersion) <= 0;
```
Comment (duncanp-sonar) [inline src/Integration/Connection/ConnectionWorkflow.cs]: _Less than or equal to_ - so SonarC# 7.0 is ok, but SonarC# 7.1 isn't? Shouldn't it be _less than major version X_? (same for VB below)

File: src/Integration/Connection/ConnectionWorkflow.cs [hunk 3]
```diff
@@ -319,10 +319,43 @@ private string GetPluginProjectMismatchErrorMessage(ICollection<EnvDTE.Project>
         private bool IsSonarQubePluginSupported(IEnumerable<SonarQubePlugin> plugins, MinimumSupportedSonarQubePlugin minimumSupportedPlugin)
         {
             var plugin = plugins.FirstOrDefault(x => StringComparer.Ordinal.Equals(x.Key, minimumSupportedPlugin.Key));
-            var isPluginSupported = !string.IsNullOrWhiteSpace(plugin?.Version) && VersionHelper.Compare(plugin.Version, minimumSupportedPlugin.MinimumVersion) >= 0;
 
-            var pluginSupportMessageFormat = string.Format(Strings.SubTextPaddingFormat, isPluginSupported ? Strings.SupportedPluginFoundMessage : Strings.UnsupportedPluginFoundMessage);
-            this.host.Logger.WriteLine(pluginSupportMessageFormat, minimumSupportedPlugin.ToString());
+            if (plugin == null) // plugin is not installed on remote server
```
Comment (duncanp-sonar) [inline src/Integration/Connection/ConnectionWorkflow.cs]: Unit tests?

File: src/Integration/Connection/ConnectionWorkflow.cs (hunk 2 above)
Comment (Evangelink) [reply src/Integration/Connection/ConnectionWorkflow.cs]: It should 👍

File: src/Integration/Connection/ConnectionWorkflow.cs (hunk 3 above)
Comment (Evangelink) [reply src/Integration/Connection/ConnectionWorkflow.cs]: Arg....

Comment (Evangelink) [reply src/Integration/Connection/ConnectionWorkflow.cs]: @duncanp-sonar done!
