### PR TITLE
Fix object disposed exception thrown intermittently by tagger

### LINKED ISSUE #1693: Object disposed exception thrown by tagger
### Description

The preview pane of the "Map" view in the editor scroll bar can cause an "object disposed" error to be thrown:

```
// inside FilteringBaseTagger.GetTags when calling aggregator.GetTags:

    at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GetTags(NormalizedSnapshotSpanCollection snapshotSpans)
   at SonarLint.VisualStudio.IssueVisualization.Editor.FilteringTaggerBase`2.<GetTags>d__15.MoveNext() in D:\repos\sq\slvs\src\IssueViz\Editor\FilteringTaggerBase.cs:line 125
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
```

#### Repro
1. Open a file with analyzed issues
2. Turn on map view
image
3. Hover over the scroll bar so the code preview appears, then move the mouse so the preview disappears

#### Expected:
The taggers and error reporting continue to behave as normal.

#### Actual:
The error tagger is disposed when the preview pane disappears, causing an exception when it is later accessed.
Tags no longer appear for the file and issues do not appear in the error list until the file is closed and re-opened.

image

### Notes
The preview View creates aggregators to access e.g. our buffer error tagger. We create only one error tagger per buffer.
When the preview View disappears, it is disposed, which in turn disposes the aggregator and our singleton-per-buffer tagger.

This problem didn't occur with the old tagging code because it the TBIT was a view tagger that reference-counted the number of views that were created, and was only disposed when all of the views had closed.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #1693

### CODE REVIEW

File: src/IssueViz/Editor/FilteringTaggerBase.cs [hunk 1]
```diff
@@ -120,6 +120,17 @@ private void OnAggregatorTagsChanged(object sender, BatchedTagsChangedEventArgs
...
         public IEnumerable<ITagSpan<TTagType>> GetTags(NormalizedSnapshotSpanCollection spans)
         {
+            if (disposedValue)
+            {
+                // See https://github.com/SonarSource/sonarlint-visualstudio/issues/1693
+                // Intermittently GetTags gets called even after the tagger instance has been
+                // disposed. We don't want an exception to be thrown in this case as it causes
+                // a gold bar to appear. To the user, it would look like the bug is in our code,
+                // whereas in fact VS has disposed the tagger but is continuing to call it.
+                Debug.Fail($"GetTags called on disposed tagger. Tagger type: {this.GetType().FullName}. File: { GetSnapshot().TextBuffer.GetFilePath()}");
```
Comment (rita-g-sonarsource) [inline src/IssueViz/Editor/FilteringTaggerBase.cs:130]: I think the Debug.Fail will be noisy. We can't do anything with it, that's VS's behavior. I think we should just do `yield break`.

**Review by rita-g-sonarsource — APPROVED** [review]

File: src/IssueViz/Editor/FilteringTaggerBase.cs (hunk 1 above)
Comment (duncanp-sonar) [reply src/IssueViz/Editor/FilteringTaggerBase.cs:130]: Yep, it will be noisy when it happens. I was undecided between `Debug.Fail` and `Debug.WriteLine` and decided to start with `Fail` because I want to assess how often this actually occurs and what the impact is.
I'll change the committed version to `WriteLine` and keep the `Fail` on my machine for now.

Comment (rita-g-sonarsource) [reply src/IssueViz/Editor/FilteringTaggerBase.cs]: But why do you need the debug at all? What will you do with the information?

Comment (duncanp-sonar) [reply src/IssueViz/Editor/FilteringTaggerBase.cs]: I'm interested in two things: 1) does it happen in real world usage, and 2) if so does it have a noticeable impact on the user experience.
