### PR TITLE
Handle Open in IDE on standalone mode

### LINKED ISSUE #5441: Handle `Open in IDE` on standalone mode
When in standalone mode, Open in IDE fails, which is indicated by sending `noBindingSuggestionFound` from sloop to slvs, but we don't handle it

### PR DESCRIPTION
**Pull request by vnaskos-sonar**
Fixes #5441

### CODE REVIEW

File: src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+    [DataRow(SonarLintMode.Standalone, true)]
+    [DataRow(SonarLintMode.Connected, false)]
+    public void Notify_ShowsMessage(SonarLintMode sonarLintMode, bool promptToConnect)
+    {
+        var notificationService = Substitute.For<INotificationService>();
+
+        var testSubject = CreateTestSubject(sonarLintMode: sonarLintMode, notificationService: notificationService);
+        testSubject.Notify();
+
+        if (promptToConnect)
```
Comment (georgii-borovinskikh-sonarsource) [inline src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs:71]: the assert looks kind of complicated because of the parameter, IMO it would be better to split the test in two

**Review by georgii-borovinskikh-sonarsource — APPROVED** [review]
LGTM, just one minor comment
