### PR TITLE
[DO NOT SQUASH] Fix #801: updating a bound solution failed in TfVC

### LINKED ISSUE #801: [TFS] Updating an existing binding fails
### Description

Updating an existing binding fails when the source control system is TfVC.
It works correctly for Git.

### Repro steps

1. Create a solution, commit it to TfVC, and bind the solution to SonarQube.

2. Go to the SonarQube pane in the _Team Explorer_ and select _Update_

### Expected behavior

The binding update succeeds.

### Actual behavior

The update fails. The following gold bar is displayed.

image

There is no useful information in the output window.

image

### Known workarounds

Manually check out the files under the _.sonarlint_ folder before updating the binding:

image

### Related information

* SonarLint for VS Version: 4.7
* Visual Studio Version: VS2015 and VS2017, all SKUs
* Languages affected: C\, VB

### Notes
On debugging, the failure is happening when attempting to check the files for edit in [this line](https://github.com/SonarSource/sonarlint-visualstudio/blob/aadf9950c7d2eb3a6978738e071de752a4fcd1f5/src/Integration/LocalServices/SourceControlledFileSystem.cs#L159).
The error code that is returned is ok so the code does not throw.
However, the _verdict_ is not _QER_EditOK_ so the method returns 
The [_moreInfo_](https://docs.microsoft.com/cs-cz/dotnet/api/microsoft.visualstudio.shell.interop.tagvsqueryeditresultflags?view=visualstudiosdk-2017) value is 272 i.e. QER_ReadOnlyUnderScc | QER_NoisyCheckoutRequired

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixed #801

### CODE REVIEW

**Comment by duncanp-sonar** [comment]
There are two commits, and I'd suggest reviewing them separately.
The first just adds logging of error messages from our source-controlled file system wrapper.
The second (much smaller change) fixes the bug.

File: src/Integration/LocalServices/SourceControlledFileSystem.cs [hunk 1]
```diff
@@ -146,7 +152,10 @@ void IFileSystem.CreateDirectory(string path)
         #region Helpers
         private bool CheckoutForEdit(params string[] fileNames)
         {
-            VsQueryEditFlags flags = VsQueryEditFlags.SilentMode | VsQueryEditFlags.DetectAnyChangedFile;
+            VsQueryEditFlags flags = VsQueryEditFlags.SilentMode | VsQueryEditFlags.DetectAnyChangedFile |
+                // Force no prompting here to fix SLVS#801 (otherwise TFS would prompt about the slconfig
+                // and generated ruleset files in new connected mode that are not in the solution)
+                VsQueryEditFlags.ForceEdit_NoPrompting;
```
Comment (duncanp-sonar) [inline src/Integration/LocalServices/SourceControlledFileSystem.cs]: This is the bug fix - passing an extra flag.

I've manually tested the change in VS2017 on solution that are not in SCC, in Git and in TfVC.
