### PR TITLE
Fix ETW ArrayTypeMismatch exception

### LINKED ISSUE #2952: ArrayTypeMismatch exception in ETW
```
ThreadID="15,728"
ProcessorNumber="1" 
message="EventSourceException while processing event "ReportSuppressionsStop": System.ArrayTypeMismatchException:Attempted to access an element as a type incompatible with the array." 
FormattedMessage="EventSourceException while processing event "ReportSuppressionsStop": System.ArrayTypeMismatchException:Attempted to access an element as a type incompatible with the array."
ActivityID="00018849-0001-0000-ec82-0000ffdcd7b5" 
```

image

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #2952

### CODE REVIEW

**Comment by duncanp-sonar** [comment]
With this fix the new events seem to be recorded correctly, although the number of suppressions looks suspiciously high and needs to be investigated (VS is configured just to analyse the current file, and there are only three suppressions listed in the file):

image

File: src/Core/ETW/CodeMarkers.cs [hunk 1]
```diff
@@ -179,14 +179,21 @@ private void Write(int id)
         }
 
         [NonEvent]
-        private void Write(int id, params string[] texts)
+        private void Write(int id, string text)
         {
             if (IsEnabled())
             {
-                WriteEvent(id, texts);
+                WriteEvent(id, text);
```
Comment (rita-sonarsource) [inline src/Core/ETW/CodeMarkers.cs:186]: Why didn't it work before? Is it because the params array got passed as an array as well? So it ended up being array of array?

I'm guessing that this is because the base method accepts `params object[]`. What if we were to cast our array to object before sending?
I.e. `WriteEvent(texts.Cast<Object>().ToArray())`. If it works then we can keep our params method.

**Review by rita-sonarsource — COMMENTED** [review]
Please see my comment, maybe there is another workaround. If not then LGTM.

**Comment by rita-sonarsource** [comment]
> With this fix the new events seem to be recorded correctly, although the number of suppressions looks suspiciously high and needs to be investigated (VS is configured just to analyse the current file, and there are only three suppressions listed in the file):
> 
> image
> 

This explains why I didn't see all the events. I suspected that something was throwing but I thought it was the supression matching. Thanks for fixing!

File: src/Core/ETW/CodeMarkers.cs (hunk 1 above)
Comment (duncanp-sonar) [reply src/Core/ETW/CodeMarkers.cs:186]: Yes, that's probably what was happening. We don't need to cast the array, we just need to change our overload to accept `params object[]`.

**Comment by duncanp-sonar** [comment]
Passing the suppression count as an `int` to the `params object[]` array fixes the problem with the number being recorded:
image

The numbers 48, 49, 50 that were being shown in PerfView before are the ASCII codes for 0, 1, 2.
