### PR TITLE
Make SonarCloud use won't fix

### LINKED ISSUE #5100: Make SonarCloud use won't fix

### PR DESCRIPTION
**Pull request by ugras-ergun-sonarsource**
Fixes #5100

### CODE REVIEW

File: src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs [hunk 1]
```diff
@@ -88,7 +88,7 @@ public bool IsAcceptTransitionAvailable()
         {
             var serverInfo = sonarQubeService.GetServerInfo();
```
Comment (georgii-borovinskikh-sonarsource) [inline src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs:89]: This is not enough. You need to change the request configuration as well

**Review by georgii-borovinskikh-sonarsource — CHANGES_REQUESTED** [review]
