### PR TITLE
Fix Roslyn suppressions handling

### LINKED ISSUE #4480: C#/VB.NET issues are not suppressed in unintrusive Connected Mode
### Description

C# and VB.NET issues are not suppressed correctly in the new unintrusive Connected Mode.

Affects v7 pre-release.

### Repro
1. Open a bound solution
2. Open a file with suppressed C# issues

### Expected
The issues are not visible in the `Error List`.

### Actual
The issues are visible in the `Error List`.

#### Investigation
The problem is that naming and location of the binding files has changed - see #4188.

There are two parts to the fix:
1) the `SuppressionExecutionContext ` needs [to be updated](https://github.com/SonarSource/sonarlint-visualstudio/blob/5cd8033fbb2cde08c631cfaaf5851fabcfa11f16/src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionExecutionContext.cs#L34) to look in a different location

2) the `RoslynSettingsFileStorage` needs to be [updated](https://github.com/SonarSource/sonarlint-visualstudio/blob/5cd8033fbb2cde08c631cfaaf5851fabcfa11f16/src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs#L104) to write the file using the solution name rather than the `Sonar` project key.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
Fixes #4480

### CODE REVIEW

File: src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs [hunk 1]
```diff
@@ -105,21 +110,23 @@ public void OnSuppressionsUpdateRequested_StandaloneMode_StorageNotUpdated()
         [DataRow(false)] // should update storage even when there are no issues
         public void OnSuppressionsUpdateRequested_ConnectedMode_StorageUpdated(bool hasIssues)
         {
-            var roslynSettingsFileStoragerage = new Mock<IRoslynSettingsFileStorage>();
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs:108]: Miscellaneous: fix typo

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileInfo.cs [hunk 2]
```diff
@@ -28,12 +28,13 @@ internal static class RoslynSettingsFileInfo
         public static readonly string Directory = PathHelper.GetTempDirForTask(false, "Roslyn");
 
         /// <summary>
-        /// Returns the full file path for the given project key
+        /// Returns the full file path for the given solution name
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileInfo.cs:31]: No code changes: I just updated the variable names and comments to make it clearer that we're working with a solution name, not a Sonar project key.

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileInfo.cs [hunk 3]
```diff
@@ -28,12 +28,13 @@ internal static class RoslynSettingsFileInfo
...
         /// </summary>
+        /// <param name="solutionName">The solution name without the file extension e.g. "MySolution"</param>
         /// <remarks> File will be in a shared location and would be able to be accessed by multiple instances of VS simulateneously</remarks>
-        public static string GetSettingsFilePath(string sonarProjectKey)
+        public static string GetSettingsFilePath(string solutionName)
         {
-            var escapedName = PathHelper.EscapeFileName(NormalizeKey(sonarProjectKey));
+            var escapedName = PathHelper.EscapeFileName(NormalizeKey(solutionName));
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileInfo.cs:37]: Strictly speaking it shouldn't be necessary to call `PathHelper.EscapeFileName` since we are expecting to be passed in a file name.
However, it was an unnecessary change at this point so I left it as-is.

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs [hunk 4]
```diff
@@ -31,7 +31,10 @@ namespace SonarLint.VisualStudio.Roslyn.Suppressions.SettingsFile
 {
     internal interface IRoslynSettingsFileStorage
     {
-        void Update(RoslynSettings settings);
+        /// <summary>
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs:34]: Added doc comment

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs [hunk 5]
```diff
@@ -31,7 +31,10 @@ namespace SonarLint.VisualStudio.Roslyn.Suppressions.SettingsFile
...
+        /// Updates the Roslyn settings file on disc for the specified solution
+        /// </summary>
+        void Update(RoslynSettings settings, string solutionNameWithoutExtension);
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs:37]: We now need the simple solution name so we can save the file in the correct place.

I considered adding the solution name to the `RoslynSettings` object, but I felt it didn't belong there so I didn't.

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs [hunk 6]
```diff
@@ -87,15 +90,16 @@ public RoslynSettings Get(string settingsKey)
...
         {
             Debug.Assert(settings != null, "Not expecting settings to be null");
             Debug.Assert(!string.IsNullOrWhiteSpace(settings.SonarProjectKey), "Not expecting settings.SonarProjectKey to be null");
+            Debug.Assert(solutionNameWithoutExtension != null, "Not expecting solutionNameWithoutExtension to be null");
 
             try
             {
                 CodeMarkers.Instance.FileStorageUpdateStart();
-                var filePath = RoslynSettingsFileInfo.GetSettingsFilePath(settings.SonarProjectKey);
+                var filePath = RoslynSettingsFileInfo.GetSettingsFilePath(solutionNameWithoutExtension);
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs:102]: Previously the settings file path contained the Sonar project key; now it contains the solution name - see #4188.

I forgot it would impact the Roslyn suppressions. Kudos to @georgii-borovinskikh-sonarsource  for spotting the problem.

File: src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionExecutionContext.cs [hunk 7]
```diff
@@ -31,7 +31,7 @@ public interface ISuppressionExecutionContext
     }
     internal class SuppressionExecutionContext : ISuppressionExecutionContext
     {
-        private const string Exp = @"\\.sonarlint\\(?<sonarkey>[^\\/]+)\\(CSharp|VB)\\SonarLint.xml$";
+        private const string Exp = @"\\SonarLint for Visual Studio\\Bindings\\(?<solutionName>[^\\/]+)\\(CSharp|VB)\\SonarLint.xml$";
```
Comment (duncanp-sonar) [inline src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionExecutionContext.cs:34]: Update the regular expression to match the new file path structure.

**Comment by duncanp-sonar** [comment]
image

**Review by bigfluffycookie — APPROVED** [review]

File: src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionExecutionContextTests.cs [hunk 8]
```diff
@@ -60,14 +60,14 @@ public void SonarProjectKey_PathIsNotValid_ReturnsNull()
         }
 
         [TestMethod]
-        public void SonarProjectKey_HasMixedPaths_ReturnsKey()
+        public void SonarProjectKey_HasMixedPaths_ReturnsExpectedSolutionName()
         {
             var additionalText1 = new ConcreteAdditionalText(@"C:\project\projectKey1\CSharp\SonarLint.xml");
-            var additionalText2 = new ConcreteAdditionalText(@"C:\project\.sonarlint\projectKey2\CSharp\SonarLint.xml");            
+            var additionalText2 = new ConcreteAdditionalText(@"C:\project\SonarLint for Visual Studio\Bindings\expectedSlnName\CSharp\SonarLint.xml");
```
Comment (georgii-borovinskikh-sonarsource) [inline src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionExecutionContextTests.cs:66]: Since we're using AppData it could be more useful for future readers to see real folder structure in some or at least one of these tests

**Review by georgii-borovinskikh-sonarsource — APPROVED** [review]

File: src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionExecutionContextTests.cs (hunk 8 above)
Comment (duncanp-sonar) [reply src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionExecutionContextTests.cs:66]: Good point. I'll add a note to fix it during a hardening sprint.
