### PR TITLE
Don't shutdown eslint-bridge process when settings are updated

### LINKED ISSUE #2425: Updating settings file in the middle of an analysis causes exceptions
#### Description

When the settings file is changed, eslint-bridge server is shut down. If this happens in the middle of a running analysis, an exception appears in the output window.

### PR DESCRIPTION
**Pull request by rita-sonarsource**
Fixes #2425

### CODE REVIEW

File: src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs [hunk 1]
```diff
@@ -135,9 +135,9 @@ private async void ActiveSolutionTracker_ActiveSolutionChanged(object sender, Ac
             await StopServer();
         }
 
-        private async void AnalysisConfigMonitor_ConfigChanged(object sender, EventArgs e)
+        private void AnalysisConfigMonitor_ConfigChanged(object sender, EventArgs e)
         {
-            await StopServer();
+            RequireLinterUpdate();
```
Comment (rita-sonarsource) [inline src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs:140]: In terms of performance, there is no reason to shutdown the entire process when settings are changed, only when the solution is changed.
Restarting the server can take about 10 seconds, so this was very inefficient (and was also causing exceptions if the settings file was saved multiple times, see #2425 )
