### PR TITLE
Fixed #760: shared projects should be excluded from binding

### LINKED ISSUE #760: [Connected mode] "Rule sets out of date" gold bar shown for shared projects
### Description

Shared projects are incorrectly reported as being out of date because they do not reference the SQ ruleset file.

### Repro steps

1. Create a solution containing a shared project and bind it to the server

2. Close and re-open the solution

### Expected behavior

The solution is up to date so there should not be a gold bar in the _Error List_ saying that an update is required.

### Actual behavior

Gold bar appears in the _Error List_ with the message:
> One or more rule sets are out of date or not linked to the SonarQube quality profile rule set. See output window (SonarLint) for affected projects."

The output window contains the following:

> DEBUGONLY: Connect workflow finished, Execution result: Succeeded
Checking for unbound projects.
Warning: could not find CodeAnalysisRuleSet for project 'SharedCode\SharedCode.shproj'
1 unbound projects were found (SharedCode\SharedCode.shproj).

### Known workarounds

None.

### Related information

* SonarLint for VS Version: all (up to 4.6 so far)
* VS2017 v15.8.6

### Notes
Shared projects are ignored during binding (so the ruleset isn't added to the project). However, shared projects don't seem to be ignored when checking whether the solution is up to date or not.

### PR DESCRIPTION
**Pull request by duncanp-sonar**
There is a separate issue with regard to test projects not being correctly recognized.
I've created #785 to track that bug, and I'm investigating another test project issue.

### CODE REVIEW

File: src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs [hunk 1]
```diff
@@ -336,6 +336,29 @@ public void ProjectSystemFilter_SetTestRegex_ArgCheck()
             Exceptions.Expect<ArgumentNullException>(() => testSubject.SetTestRegex(null));
         }
 
+        [TestMethod]
+        public void ProjectSystemFilter_IsAccepted_UnrecognisedProjectType_ReturnsFalse()
```
Comment (duncanp-sonar) [inline src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs]: This first test is not related to the fix. I could find any tests that covered non-VB/CS projects so I added this one.

File: src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs [hunk 2]
```diff
@@ -346,6 +369,15 @@ private ProjectSystemFilter CreateTestSubject()
             return new ProjectSystemFilter(host);
         }
 
+        private void CheckProjectIsNotAccepted(ProjectMock project)
+        {
+            var testSubject = this.CreateTestSubject();
+
+            var result = testSubject.IsAccepted(project);
+
+            result.Should().BeFalse();
```
Comment (valhristov) [inline src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs]: I think this method is not generally needed, it saves two lines and IMO the code in the tests is harder to understand
