### PR TITLE
Ensure InitLinter is called when new EslintBridgeProcess is spawned

### LINKED ISSUE #2409: init-linter is not called again when eslint-bridge process crashes
#### Description

Analysis will fail if eslint-bridge process crashes after the server was initialized successfully with init-linter.

Steps to reproduce:
1. Analyze a ts file --> eslint-bridge process starts, init-linter is called, analysis is successful
2. Open task manager and kill nodejs processes under Visual Studio
3. Re-analyze a ts file

Expected --> analysis is successful
Actual --> analysis fails with `GENERAL_ERROR Linter is undefined. Did you call /init-linter?`
Subsequent analysis also fails.

### PR DESCRIPTION
**Pull request by rita-sonarsource**
Fixes #2409

### CODE REVIEW

File: src/TypeScript/Analyzer/TypeScriptAnalyzer.cs [hunk 1]
```diff
@@ -150,6 +150,10 @@ internal async Task ExecuteAnalysis(string filePath, IIssueConsumer consumer, Ca
                     consumer.Accept(filePath, issues);
                 }
             }
+            catch (EslintBridgeClientNotInitializedException)
```
Comment (rita-sonarsource) [inline src/TypeScript/Analyzer/TypeScriptAnalyzer.cs:153]: The analysis will fail but the next call will succeed.
I'll handle it better as part of #2190
